// Canonical Top Localities, Wards & Industrial Hubs for Indian Metropolitan & Tier-2/Tier-3 Cities
// Enables exhaustive multi-area search across Justdial, Sulekha, Grotal, IndiaMART, TradeIndia
// Compiled from municipal corporation master plans, census urban agglomerations, and Wikipedia administrative registers.

export const CITY_AREAS = {
  "osmanabad": ["MIDC Osmanabad", "Samata Nagar", "Shivaji Chowk", "Tuljapur Road"],
  "bijapur": ["Station Road", "Gandhi Chowk", "Solapur Road", "Athani Road", "Navraspur"],
  "puducherry": ["White Town", "Heritage Town", "MG Road", "Anna Salai", "Lawspet", "Auroville", "Muthialpet"],
  "delhi": [
    "Connaught Place",
    "Karol Bagh",
    "Lajpat Nagar",
    "South Extension",
    "Rohini",
    "Pitampura",
    "Dwarka",
    "Janakpuri",
    "Saket",
    "Hauz Khas",
    "Greater Kailash",
    "Vasant Kunj",
    "Nehru Place",
    "Laxmi Nagar",
    "Preet Vihar",
    "Chandni Chowk",
    "Rajouri Garden",
    "Punjabi Bagh",
    "Paschim Vihar",
    "Shahdara",
    "Malviya Nagar",
    "Defence Colony",
    "Mayur Vihar",
    "Okhla Industrial Area",
    "Patel Nagar",
    "Kalkaji",
    "Green Park",
    "Model Town",
    "Shalimar Bagh",
    "Tilak Nagar",
    "Mayapuri",
    "Wazirpur",
    "Naraina",
    "Bawana",
    "Kirti Nagar",
    "Vasant Vihar",
    "Safdarjung Enclave",
    "CR Park",
    "Alaknanda",
    "Paharganj",
    "Daryaganj",
    "Civil Lines",
    "Ashok Vihar",
    "Kamla Nagar",
    "Sadar Bazaar",
    "Narela",
    "Badarpur",
    "Mehrauli",
    "Kotla Mubarakpur",
    "Govindpuri",
    "Sultanpur",
    "Mangolpuri",
    "Shahpur Jat",
    "Khan Market",
    "Barakhamba",
    "Chanakyapuri",
    "Lodhi Colony",
    "INA Colony",
    "Sarojini Nagar"
  ],
  "gurgaon": [
    "DLF Cyber City",
    "DLF Phase 1",
    "DLF Phase 2",
    "DLF Phase 3",
    "DLF Phase 4",
    "DLF Phase 5",
    "Sector 14",
    "Sector 29",
    "Sector 44",
    "Sector 48",
    "Sector 49",
    "Sector 54",
    "Sector 56",
    "Sohna Road",
    "Golf Course Road",
    "Golf Course Extension Road",
    "MG Road",
    "Udyog Vihar Phase 1",
    "Udyog Vihar Phase 2",
    "Udyog Vihar Phase 3",
    "Udyog Vihar Phase 4",
    "Udyog Vihar Phase 5",
    "Manesar",
    "Palam Vihar",
    "Sushant Lok 1",
    "Sushant Lok 2",
    "South City 1",
    "South City 2",
    "Sector 57",
    "Sector 62",
    "Sector 65",
    "Sector 82",
    "Sector 83",
    "New Gurgaon",
    "Old Railway Road"
  ],
  "noida": [
    "Sector 18",
    "Sector 62",
    "Sector 63",
    "Sector 15",
    "Sector 16",
    "Sector 2",
    "Sector 3",
    "Sector 4",
    "Sector 5",
    "Sector 6",
    "Sector 10",
    "Sector 11",
    "Sector 12",
    "Sector 19",
    "Sector 27",
    "Sector 29",
    "Sector 50",
    "Sector 51",
    "Sector 74",
    "Sector 75",
    "Sector 76",
    "Sector 78",
    "Sector 128",
    "Sector 132",
    "Sector 135",
    "Sector 137",
    "Sector 142",
    "Noida Expressway",
    "Noida Extension",
    "Greater Noida West",
    "Knowledge Park 1",
    "Knowledge Park 2",
    "Knowledge Park 3",
    "Pari Chowk",
    "Ecotech",
    "Kasna"
  ],
  "faridabad": [
    "NIT 1",
    "NIT 2",
    "NIT 3",
    "NIT 4",
    "NIT 5",
    "Sector 15",
    "Sector 16",
    "Sector 19",
    "Sector 21",
    "Sector 28",
    "Sector 29",
    "Sector 31",
    "Sector 37",
    "Mathura Road",
    "Old Faridabad",
    "Ballabhgarh",
    "Neelam Bata Road",
    "Badkhal",
    "Surajkund",
    "Greenfield Colony",
    "Sector 14",
    "Sector 17",
    "Sector 82",
    "Sector 85",
    "Greater Faridabad"
  ],
  "ghaziabad": [
    "Indirapuram",
    "Vaishali",
    "Vasundhara",
    "Kaushambi",
    "Raj Nagar",
    "Raj Nagar Extension",
    "Kavi Nagar",
    "Crossings Republik",
    "Sahibabad",
    "Loni",
    "Mohan Nagar",
    "Vijay Nagar",
    "Patel Nagar",
    "Govindpuram",
    "Sanjay Nagar",
    "Ambedkar Road",
    "Model Town",
    "Shastri Nagar",
    "Bulandshahr Road Industrial Area",
    "Site 4 Industrial Area"
  ],
  "mumbai": [
    "Andheri West",
    "Andheri East",
    "Bandra West",
    "Bandra East",
    "Borivali West",
    "Borivali East",
    "Juhu",
    "Kandivali West",
    "Kandivali East",
    "Malad West",
    "Malad East",
    "Goregaon West",
    "Goregaon East",
    "Santacruz West",
    "Santacruz East",
    "Vile Parle West",
    "Vile Parle East",
    "Powai",
    "Ghatkopar West",
    "Ghatkopar East",
    "Mulund West",
    "Mulund East",
    "Kurla",
    "Bhandup",
    "Dadar West",
    "Dadar East",
    "Lower Parel",
    "Worli",
    "Prabhadevi",
    "Colaba",
    "Nariman Point",
    "Fort",
    "Marine Lines",
    "Churchgate",
    "Byculla",
    "Parel",
    "Chembur",
    "Sion",
    "Matunga",
    "Mahim",
    "Khar West",
    "Charni Road",
    "Girgaon",
    "Tardeo",
    "Walkeshwar",
    "Malabar Hill",
    "Cuffe Parade",
    "BKC",
    "MIDC Andheri",
    "Marol",
    "Saki Naka",
    "Chakala",
    "Lokhandwala",
    "Versova",
    "Oshiwara",
    "Dahisar West",
    "Dahisar East",
    "Vikhroli",
    "Kanjurmarg",
    "Govandi"
  ],
  "thane": [
    "Naupada",
    "Panchpakhadi",
    "Vartak Nagar",
    "Majiwada",
    "Ghodbunder Road",
    "Kasarvadavali",
    "Hiranandani Estate",
    "Hiranandani Meadows",
    "Wagle Industrial Estate",
    "Kopri",
    "Thane West",
    "Thane East",
    "Manpada",
    "Brahmand",
    "Kolshet Road",
    "Kalwa",
    "Mumbra",
    "Diva",
    "Balkum",
    "Owale",
    "Anand Nagar",
    "Louis Wadi",
    "Charai",
    "Khopat",
    "Uthalsar"
  ],
  "navi mumbai": [
    "Vashi",
    "Nerul",
    "Belapur",
    "Kharghar",
    "Kopar Khairane",
    "Airoli",
    "Ghansoli",
    "Sanpada",
    "Seawoods",
    "Ulwe",
    "Panvel",
    "New Panvel",
    "Kamothe",
    "Kalamboli",
    "Mahape",
    "Turbhe",
    "Juinagar",
    "Dronagiri",
    "Taloja",
    "MIDC Rabale",
    "MIDC TTC",
    "CBD Belapur"
  ],
  "bangalore": [
    "Koramangala",
    "Indiranagar",
    "Whitefield",
    "HSR Layout",
    "BTM Layout",
    "Jayanagar",
    "JP Nagar",
    "Electronic City Phase 1",
    "Electronic City Phase 2",
    "Marathahalli",
    "Bellandur",
    "Sarjapur Road",
    "Hebbal",
    "Yelahanka",
    "Malleshwaram",
    "Rajajinagar",
    "Banashankari",
    "Basavanagudi",
    "Sadashivanagar",
    "Frazer Town",
    "MG Road",
    "Brigade Road",
    "Commercial Street",
    "Richmond Town",
    "Ulsoor",
    "Domlur",
    "Kalyan Nagar",
    "Kammanahalli",
    "HRBR Layout",
    "Banaswadi",
    "Hennur Road",
    "Thanisandra",
    "Nagawara",
    "RT Nagar",
    "Vidyaranyapura",
    "Sahakara Nagar",
    "Yeshwanthpur",
    "Peenya Industrial Area",
    "Vijayanagar",
    "Basaveshwaranagar",
    "Mahalaxmi Layout",
    "Kengeri",
    "Rajarajeshwari Nagar",
    "Uttarahalli",
    "Bannerghatta Road",
    "Arekere",
    "Hulimavu",
    "Begur",
    "Bommanahalli",
    "Kudlu Gate",
    "Hosa Road",
    "Kasavanahalli",
    "Kadugodi",
    "Hoodi",
    "Varthur",
    "Brookefield"
  ],
  "hyderabad": [
    "Kukatpally",
    "Banjara Hills",
    "Jubilee Hills",
    "Madhapur",
    "Gachibowli",
    "Hitec City",
    "Kondapur",
    "Ameerpet",
    "Begumpet",
    "Secunderabad",
    "Dilsukhnagar",
    "LB Nagar",
    "Uppal",
    "Miyapur",
    "Nizampet",
    "KPHB Colony",
    "Chanda Nagar",
    "Manikonda",
    "Financial District",
    "Nanakramguda",
    "Kokapet",
    "Tellapur",
    "Kollur",
    "Patancheru",
    "Jeedimetla",
    "Sanathnagar",
    "Balanagar",
    "Somajiguda",
    "Panjagutta",
    "Khairatabad",
    "Lakdikapul",
    "Abids",
    "Koti",
    "Himayatnagar",
    "Narayanaguda",
    "Basheerbagh",
    "Nampally",
    "Charminar",
    "Mehdipatnam",
    "Tolichowki",
    "Attapur",
    "Rajendranagar",
    "Shamshabad",
    "Malakpet",
    "Santosh Nagar",
    "Vanasthalipuram",
    "Hayathnagar",
    "Nagole",
    "Boduppal",
    "Peerzadiguda",
    "Habsiguda",
    "Nacharam",
    "Mallapur",
    "Moula Ali",
    "ECIL",
    "Kushaiguda",
    "AS Rao Nagar",
    "Sainikpuri",
    "Yapral",
    "Kapra",
    "Alwal",
    "Bowenpally",
    "Tirumalagiri",
    "Marredpally",
    "Karkhana",
    "Kavuri Hills",
    "Balanagar Industrial Area",
    "Cherlapally",
    "Gaddi Annaram",
    "Moosarambagh"
  ],
  "chennai": [
    "T Nagar",
    "Anna Nagar",
    "Adyar",
    "Velachery",
    "Mylapore",
    "Alwarpet",
    "Nungambakkam",
    "Besant Nagar",
    "Thiruvanmiyur",
    "Guindy",
    "OMR",
    "Sholinganallur",
    "Perungudi",
    "Thoraipakkam",
    "Navalur",
    "Siruseri",
    "Tambaram",
    "Chromepet",
    "Pallavaram",
    "Porur",
    "Ramapuram",
    "Vadapalani",
    "Koyambedu",
    "KK Nagar",
    "Ashok Nagar",
    "Kodambakkam",
    "Saidapet",
    "Egmore",
    "Kilpauk",
    "Chetpet",
    "Purasawalkam",
    "Sowcarpet",
    "George Town",
    "Royapettah",
    "Gopalapuram",
    "Triplicane",
    "Teynampet",
    "Mandaveli",
    "RA Puram",
    "Kotturpuram",
    "Madipakkam",
    "Medavakkam",
    "Perambur",
    "Kolathur",
    "Villivakkam",
    "Ambattur",
    "Avadi",
    "Poonamallee",
    "Manapakkam",
    "Red Hills",
    "Ennore",
    "Thiruvottiyur",
    "Royapuram",
    "Washermanpet",
    "Vyasarpadi"
  ],
  "kolkata": [
    "Park Street",
    "Salt Lake",
    "Salt Lake Sector 5",
    "New Town",
    "Rajarhat",
    "Ballygunge",
    "Alipore",
    "Gariahat",
    "Bhawanipur",
    "Tollygunge",
    "Jadavpur",
    "Garia",
    "Behala",
    "Kasba",
    "Ruby",
    "EM Bypass",
    "Dum Dum",
    "Lake Town",
    "Kankurgachi",
    "Ultadanga",
    "Shyambazar",
    "Hatibagan",
    "Sovabazar",
    "Bagbazar",
    "Burrabazar",
    "College Street",
    "Bowbazar",
    "Esplanade",
    "Chandni Chowk",
    "BBD Bagh",
    "Sealdah",
    "Howrah Station",
    "Dharmatala",
    "Ripon Street",
    "Camac Street",
    "Theatre Road",
    "Elgin Road",
    "Lansdowne",
    "Southern Avenue",
    "Kalighat",
    "Rashbehari",
    "Chetla",
    "New Alipore",
    "Taratala",
    "Khardah",
    "Sodepur",
    "Barasat",
    "Madhyamgram",
    "Kestopur",
    "Baguiati",
    "VIP Road",
    "Chinar Park",
    "Action Area 1",
    "Action Area 2",
    "Action Area 3"
  ],
  "pune": [
    "Kothrud",
    "Baner",
    "Aundh",
    "Wakad",
    "Hinjawadi",
    "Viman Nagar",
    "Kalyani Nagar",
    "Koregaon Park",
    "Hadapsar",
    "Magarpatta",
    "Shivajinagar",
    "FC Road",
    "JM Road",
    "Deccan Gymkhana",
    "Camp",
    "MG Road",
    "Swargate",
    "Pimple Saudagar",
    "Pimple Nilakh",
    "Bavdhan",
    "Pashan",
    "Warje",
    "Sinhagad Road",
    "Dhankawadi",
    "Katraj",
    "Bibwewadi",
    "Kondhwa",
    "Wanowrie",
    "Fatima Nagar",
    "Undri",
    "Pisoli",
    "Kharadi",
    "Wagholi",
    "Chandan Nagar",
    "Yerwada",
    "Dighi",
    "Bhosari",
    "Pimpri",
    "Chinchwad",
    "Akurdi",
    "Nigdi",
    "Ravet",
    "Tathawade",
    "Punawale",
    "Moshi",
    "Chakan",
    "Talegaon",
    "Pirangut",
    "Khadki",
    "Dapodi",
    "Kasarwadi",
    "Fursungi",
    "Manjri",
    "Loni Kalbhor",
    "Saswad"
  ],
  "ahmedabad": [
    "Navrangpura",
    "Satellite",
    "Bodakdev",
    "Vastrapur",
    "Prahlad Nagar",
    "SG Highway",
    "Thaltej",
    "Bopal",
    "South Bopal",
    "Shela",
    "Gota",
    "Chandkheda",
    "Motera",
    "Sabarmati",
    "Ranip",
    "Naranpura",
    "Memnagar",
    "Ambawadi",
    "Ellisbridge",
    "Paldi",
    "Vasna",
    "Maninagar",
    "Kankaria",
    "Ghanshyam Nagar",
    "Isanpur",
    "Naroda",
    "Odhav",
    "Vatva",
    "Nikol",
    "Bapunagar",
    "Asarwa",
    "Shahibaug",
    "Camp",
    "Civil Hospital",
    "Ghanshyamnagar",
    "C G Road",
    "Ashram Road",
    "Sindhu Bhavan Road",
    "Science City Road",
    "Sanand"
  ],
  "nagpur": [
    "Dharampeth",
    "Ramdaspeth",
    "Civil Lines",
    "Sadar",
    "Sitabuldi",
    "Dhantoli",
    "Wardha Road",
    "Pratap Nagar",
    "Manish Nagar",
    "Besur",
    "Nandanvan",
    "Sakkardara",
    "Mahal",
    "Gandhibagh",
    "Itwari",
    "Kalamna",
    "MIDC Hingna",
    "Butibori",
    "Trimurti Nagar",
    "Bajaj Nagar",
    "Laxmi Nagar"
  ],
  "nashik": [
    "College Road",
    "Gangapur Road",
    "Indira Nagar",
    "CIDCO",
    "Satpur MIDC",
    "Ambad MIDC",
    "Panchavati",
    "Nashik Road",
    "Dwarka",
    "Rane Nagar",
    "Govind Nagar",
    "Mahatma Nagar",
    "Pathardi Phata",
    "Jail Road",
    "Deolali Camp",
    "Sinnar MIDC",
    "Parijat Nagar"
  ],
  "aurangabad": [
    "Cidco",
    "Nirala Bazar",
    "Cannaught Place",
    "Waluj MIDC",
    "Chikalthana MIDC",
    "Shendra MIDC",
    "Railway Station Road",
    "Kranti Chowk",
    "Garkheda",
    "Seven Hills",
    "Jalna Road",
    "Beed Bypass",
    "Samarth Nagar",
    "Shahgunj",
    "Osmanpura",
    "Aurangpura",
    "Bajaj Nagar"
  ],
  "solapur": [
    "Hotgi Road",
    "Jule Solapur",
    "Saat Rasta",
    "Old Pune Naka",
    "Navi Peth",
    "Budhwar Peth",
    "MIDC Chincholi",
    "Kegaon",
    "Bhavani Peth",
    "Ashok Chowk",
    "Railway Lines",
    "Lashkar"
  ],
  "kolhapur": [
    "Rajarampuri",
    "Tarabai Park",
    "Shahupuri",
    "Nagala Park",
    "Laxmipuri",
    "Shiroli MIDC",
    "Gokul Shirgaon MIDC",
    "Rankala",
    "Ruikar Colony",
    "Kadamwadi",
    "Bapat Camp",
    "Gandhinagar"
  ],
  "nanded": [
    "Vazirabad",
    "Shivaji Nagar",
    "Taroda Naka",
    "CIDCO Nanded",
    "MIDC Nanded",
    "Workshop Corner"
  ],
  "sangli": [
    "Vishrambag",
    "Kupwad MIDC",
    "Miraj",
    "Gaon Bhag",
    "Haripur",
    "Madhavnagar"
  ],
  "amravati": [
    "Camp",
    "Rajapeth",
    "Badnera",
    "MIDC Amravati",
    "Gadge Nagar",
    "Rathi Nagar"
  ],
  "jalgaon": [
    "MIDC Jalgaon",
    "Navi Peth",
    "Ring Road",
    "Court Road",
    "Pratap Nagar"
  ],
  "akola": [
    "Civil Lines",
    "MIDC Phase 1",
    "Ratanlal Plot",
    "Ramdas Peth",
    "Jatharpeth"
  ],
  "latur": [
    "Ausa Road",
    "MIDC Latur",
    "Shivaji Chowk",
    "Gandhi Market",
    "Khadgaon Road"
  ],
  "satara": [
    "MIDC Satara",
    "Powi Naka",
    "Rajwada",
    "Koregaon",
    "Wai",
    "Karad"
  ],
  "ahmednagar": [
    "Savedi",
    "MIDC Nagapur",
    "Station Road",
    "Delhi Gate",
    "Market Yard"
  ],
  "dhule": [
    "Deopur",
    "MIDC Awadhan",
    "Agra Road",
    "Sakri Road",
    "Chitod Road"
  ],
  "chandrapur": [
    "MIDC Tadoba Road",
    "Civil Lines",
    "Ram Nagar",
    "Bazar Ward",
    "Ballarpur"
  ],
  "jalna": [
    "MIDC Jalna",
    "Old Jalna",
    "New Jalna",
    "Mantha Road",
    "Devalgaon Raja Road"
  ],
  "ratnagiri": [
    "MIDC Mirjole",
    "Nachane",
    "Salvi Stop",
    "Mandvi",
    "Zadgaon"
  ],
  "surat": [
    "Adajan",
    "Vesu",
    "Piplod",
    "Varachha",
    "Katargam",
    "Ring Road",
    "Athwa Lines",
    "Ghod Dod Road",
    "City Light",
    "Rander",
    "Pal",
    "Dindoli",
    "Udhna",
    "Sachin GIDC",
    "Pandesara GIDC",
    "Hazira",
    "Nanpura",
    "Bhatar",
    "Majura Gate",
    "Althan",
    "Kamrej",
    "Amroli",
    "Begumpura"
  ],
  "vadodara": [
    "Alkapuri",
    "Akota",
    "Fatehgunj",
    "Gotri",
    "Vasna Road",
    "Old Padra Road",
    "Karelibaug",
    "Manjalpur",
    "Makarpura GIDC",
    "Waghodia Road",
    "Sayajigunj",
    "Gorwa",
    "Subhanpura",
    "Nizampura",
    "Harni",
    "Sama",
    "Ellora Park",
    "Sun Pharma Road",
    "Nandesari GIDC",
    "Por GIDC"
  ],
  "rajkot": [
    "Kalawad Road",
    "Yagnik Road",
    "University Road",
    "150 Feet Ring Road",
    "Kotecha Chowk",
    "Nana Mava",
    "Mota Mava",
    "Bhaktinagar",
    "Aji GIDC",
    "Metoda GIDC",
    "Shapar Veraval",
    "Dhebar Road",
    "Gondal Road",
    "Madhapar",
    "Raiya Road",
    "Kasturba Road"
  ],
  "bhavnagar": [
    "Waghawadi Road",
    "Kalanala",
    "Chitra GIDC",
    "Ghogha Circle",
    "Subhashnagar",
    "Kaliybid"
  ],
  "jamnagar": [
    "Digjam Plot",
    "Patel Colony",
    "GIDC Phase 1",
    "GIDC Phase 2",
    "Bedeshwar",
    "Indira Marg"
  ],
  "junagadh": [
    "Zanzarda Road",
    "Kalva Chowk",
    "Motibaug",
    "GIDC Junagadh",
    "Joshipura"
  ],
  "gandhinagar": [
    "Sector 11",
    "Sector 21",
    "Infocity",
    "GIFT City",
    "Kudasan",
    "Randesan",
    "Sargasan"
  ],
  "anand": [
    "Vidyanagar",
    "Amul Dairy Road",
    "GIDC Vithal Udyognagar",
    "Station Road",
    "100 Feet Road"
  ],
  "morbi": [
    "Trajpar",
    "Lakhdhirpur Road",
    "8-A National Highway",
    "GIDC Morbi",
    "Sanala Road"
  ],
  "vapi": [
    "GIDC Vapi",
    "Charwada",
    "Dungra",
    "Gunjan",
    "Koparli Road",
    "Silvassa Road"
  ],
  "ankleshwar": [
    "GIDC Ankleshwar",
    "Station Road",
    "Jitali",
    "Valia Road",
    "Piraman"
  ],
  "bharuch": [
    "Zadeshwar Road",
    "Link Road",
    "Station Road",
    "Bholav",
    "Narmada Nagar"
  ],
  "navsari": [
    "Lunsikui",
    "Jalalpor",
    "Station Road",
    "GIDC Navsari",
    "Vijalpore"
  ],
  "porbandar": [
    "MG Road",
    "Chhaya",
    "GIDC Porbandar",
    "Subhash Nagar",
    "Khadia"
  ],
  "gandhidham": [
    "Sector 1",
    "Sector 8",
    "Tagore Road",
    "Oslo",
    "Adipur",
    "Kandla Port"
  ],
  "mehsana": [
    "GIDC Mehsana",
    "Radhanpur Road",
    "Modhera Road",
    "Highway",
    "Pilaji Ganj"
  ],
  "himatnagar": [
    "Motipura",
    "GIDC Himatnagar",
    "Mahavirnagar",
    "Station Road"
  ],
  "palanpur": [
    "Aroma Circle",
    "GIDC Palanpur",
    "Delhi Gate",
    "Deesa Highway"
  ],
  "mysore": [
    "Gokulam",
    "VV Mohalla",
    "Jayalakshmipuram",
    "KRS Road",
    "Hebbal Industrial Area",
    "Hootagalli",
    "Kuvempunagar",
    "Saraswathipuram",
    "Siddhartha Layout",
    "Bannimantap",
    "Vijayanagar",
    "Yadavagiri"
  ],
  "hubli": [
    "Vidyanagar",
    "Gokul Road",
    "Tarihal Industrial Area",
    "Keshwapur",
    "Dharwad",
    "Navanagar",
    "Rayapur"
  ],
  "mangalore": [
    "Kadri",
    "Kodialbail",
    "Lalbagh",
    "Hampankatta",
    "Baikampady Industrial Area",
    "Bejai",
    "Kankanady",
    "Surathkal"
  ],
  "belgaum": [
    "Tilakwadi",
    "Khanapur Road",
    "Udyambag",
    "Camp",
    "Hindwadi",
    "Auto Nagar",
    "Machhe"
  ],
  "gulbarga": [
    "Sedam Road",
    "MSK Mill Road",
    "Station Road",
    "Humnabad Base",
    "Kapnoor Industrial Area"
  ],
  "bellary": [
    "Cantonment",
    "Infantry Road",
    "Anantapur Road",
    "Toranagallu",
    "Patel Nagar"
  ],
  "davanagere": [
    "MCC A Block",
    "MCC B Block",
    "PB Road",
    "KTJ Nagar",
    "Anjaneya Badavane"
  ],
  "shimoga": [
    "Vinoba Nagar",
    "Gopala",
    "Kallihal Industrial Area",
    "Durgigudi",
    "Sagar Road"
  ],
  "tumkur": [
    "Kyathsandra",
    "Sira Road",
    "Vasanthanarasapura Industrial Area",
    "Batawadi",
    "Ashok Nagar"
  ],
  "udupi": [
    "Manipal",
    "Kalsanka",
    "Diana Circle",
    "Brahmagiri",
    "Santhekatte",
    "Malpe"
  ],
  "hassan": [
    "Kuvempu Nagar",
    "Hassan Industrial Area",
    "Boovanahalli",
    "Vidya Nagar"
  ],
  "raichur": [
    "Station Road",
    "Askihal",
    "Raichur Industrial Area",
    "Nijalingappa Colony"
  ],
  "bidar": [
    "Naubad Industrial Area",
    "Gandhi Gunj",
    "Shivaji Chowk",
    "Mailoor"
  ],
  "kolar": [
    "Tamaka",
    "Gauribidanur Road",
    "Bangarapet",
    "KGF",
    "Robertsonpet"
  ],
  "hospet": [
    "College Road",
    "Station Road",
    "Dam Road",
    "Hampi Road",
    "Amaravathi"
  ],
  "coimbatore": [
    "RS Puram",
    "Gandhipuram",
    "Peelamedu",
    "Saibaba Colony",
    "Saravanampatti",
    "Ramanathapuram",
    "Singanallur",
    "Race Course",
    "Avinashi Road",
    "Ganapathy",
    "Trichy Road",
    "Vadavalli",
    "Ukkadam",
    "Kuniyamuthur",
    "Sundarapuram",
    "Thudiyalur",
    "SIDCO Kurichi",
    "Kovaipudur"
  ],
  "madurai": [
    "KK Nagar",
    "Anna Nagar",
    "Simmakkal",
    "Goripalayam",
    "Tallakulam",
    "Sellur",
    "Mattuthavani",
    "TVS Nagar",
    "Villapuram",
    "Thirunagar",
    "Kappalur Industrial Estate",
    "Palanganatham"
  ],
  "trichy": [
    "Thillai Nagar",
    "Cantonment",
    "Srirangam",
    "K K Nagar",
    "Central Bus Stand",
    "Main Guard Gate",
    "Thiruverumbur",
    "BHEL Township",
    "Palakkarai",
    "Ponmalai",
    "Karumandapam",
    "Woraiyur"
  ],
  "salem": [
    "Fairlands",
    "Hasthampatti",
    "Alagapuram",
    "Suramangalam",
    "Shevapet",
    "Meyyanur",
    "Five Roads",
    "Ammapet",
    "Junction",
    "Steel Plant Road",
    "Seelanaickenpatti"
  ],
  "tiruppur": [
    "Avinashi Road",
    "Palladam Road",
    "Kangeyam Road",
    "Dharapuram Road",
    "Uthukuli Road",
    "SIDCO Mudalipalayam"
  ],
  "erode": [
    "Perundurai Road",
    "Brough Road",
    "Mettur Road",
    "Sathy Road",
    "Chithode",
    "SIPCOT Perundurai"
  ],
  "vellore": [
    "Katpadi",
    "Sathuvachari",
    "Gandhi Nagar",
    "Bagayam",
    "Arcot Road",
    "Ranipet SIPCOT"
  ],
  "tirunelveli": [
    "Palayamkottai",
    "Junction",
    "Town",
    "Vannarpettai",
    "Melapalayam",
    "SIPCOT Gangaikondan"
  ],
  "thoothukudi": [
    "Palayamkottai Road",
    "Bryant Nagar",
    "Millerpuram",
    "SIPCOT Tuticorin",
    "Harbour"
  ],
  "thanjavur": [
    "Medical College Road",
    "Yagappa Nagar",
    "New Bus Stand",
    "Vallam",
    "South Rampart"
  ],
  "dindigul": [
    "Palani Road",
    "Nagal Nagar",
    "Trichy Road",
    "Batlagundu Road",
    "Round Road"
  ],
  "hosur": [
    "SIPCOT 1",
    "SIPCOT 2",
    "Bagalur Road",
    "Rayakottai Road",
    "Mookandapalli",
    "Denkanikottai Road"
  ],
  "karur": [
    "Kovai Road",
    "Jawahar Bazaar",
    "Vengamedu",
    "Thanthonimalai",
    "LNS Post"
  ],
  "nagercoil": [
    "Court Road",
    "Vadasery",
    "Kottar",
    "Chetti Kulam",
    "Parvathipuram"
  ],
  "kanchipuram": [
    "Gandhi Road",
    "Ennaikaran",
    "Orikkai",
    "Kaveripakkam",
    "Sunguvarchatram"
  ],
  "warangal": [
    "Hanamkonda",
    "Kazipet",
    "Subedari",
    "Nayeem Nagar",
    "Kishanpura",
    "Balasamudram",
    "Hunter Road"
  ],
  "nizamabad": [
    "Khaleelwadi",
    "Bodhan Road",
    "Armoor",
    "Station Road",
    "Subhashnagar",
    "Goutham Nagar"
  ],
  "karimnagar": [
    "Collectorate Road",
    "Mukarrampura",
    "Kothapalli",
    "Mankammathota",
    "Jyothinagar"
  ],
  "khammam": [
    "Wyra Road",
    "Mayuri Centre",
    "Mamillagudam",
    "Rotary Nagar",
    "Kaviraj Nagar"
  ],
  "ramagundam": [
    "NTPC Township",
    "Godavarikhani",
    "FCI",
    "Fertilizer City",
    "Jyothi Nagar"
  ],
  "mahbubnagar": [
    "Raichur Road",
    "Clock Tower",
    "Bhootpur Road",
    "Teachers Colony",
    "Christian Pally"
  ],
  "visakhapatnam": [
    "MVP Colony",
    "Gajuwaka",
    "Madhurawada",
    "Dwaraka Nagar",
    "Siripuram",
    "Seethammadhara",
    "Akkayyapalem",
    "Daba Gardens",
    "Jagadamba Junction",
    "Kurmannapalem",
    "Pendurthi",
    "NAD Junction",
    "Muralinagar",
    "Rushikonda",
    "Waltair Uplands",
    "Auto Nagar",
    "Steel Plant Township"
  ],
  "vijayawada": [
    "Benz Circle",
    "MG Road",
    "Governorpet",
    "Suryaraopet",
    "Gandhinagar",
    "Satyanarayanapuram",
    "Auto Nagar",
    "Patamata",
    "Bhavanipuram",
    "Gollapudi",
    "Gunadala",
    "Poranki",
    "Kankipadu"
  ],
  "guntur": [
    "Arundelpet",
    "Brodipet",
    "Kothapet",
    "Lakshmipuram",
    "Pattabhipuram",
    "Auto Nagar Guntur",
    "Nallapadu"
  ],
  "nellore": [
    "Dargamitta",
    "Magunta Layout",
    "Pogathota",
    "Stonehousepet",
    "Vedayapalem",
    "Haranathapuram"
  ],
  "kurnool": [
    "Nandyal Checkpost",
    "Birla Gate",
    "Gayatri Estate",
    "Budhwarpet",
    "C-Camp",
    "Santosh Nagar"
  ],
  "rajahmundry": [
    "Danavaipeta",
    "Aryapuram",
    "Innespeta",
    "Kotipalli Bus Stand",
    "Morampudi",
    "Diwancheruvu"
  ],
  "tirupati": [
    "AIR Bypass Road",
    "Alipiri",
    "Bhavani Nagar",
    "Renigunta Road",
    "Korlagunta",
    "Chandragiri"
  ],
  "kakinada": [
    "Bhanugudi Junction",
    "Suryaraopeta",
    "Gandhi Nagar",
    "Madhavapatnam",
    "Auto Nagar Kakinada"
  ],
  "anantapur": [
    "Subash Road",
    "Sapthagiri Circle",
    "Court Road",
    "Rudrampeta",
    "Maruthi Nagar"
  ],
  "kadapa": [
    "RTC Bus Stand Road",
    "Nagarajupalli",
    "Yerramukkapalli",
    "Madhavaram",
    "RIMS Road"
  ],
  "vizianagaram": [
    "Cantonment",
    "Mayuri Junction",
    "Balaji Nagar",
    "Fort Road",
    "Ring Road"
  ],
  "eluru": [
    "Powerpet",
    "RR Pet",
    "Sanivarapupeta",
    "Tangellamudi",
    "Vatluru"
  ],
  "ongole": [
    "Kurnool Road",
    "Lawyerpet",
    "Santhapeta",
    "Mangamuru Road",
    "Prakasam Bhavan"
  ],
  "kochi": [
    "MG Road",
    "Edappally",
    "Kakkanad",
    "Palarivattom",
    "Kaloor",
    "Aluva",
    "Vyttila",
    "Panampilly Nagar",
    "Fort Kochi",
    "Mattancherry",
    "Tripunithura",
    "Marine Drive",
    "Kadavanthra",
    "Angamaly",
    "Kalamassery"
  ],
  "thiruvananthapuram": [
    "Technopark",
    "Kazhakkoottam",
    "Palayam",
    "Vellayambalam",
    "Kowdiar",
    "Pattom",
    "Thampanoor",
    "East Fort",
    "Vazhuthacaud",
    "Sasthamangalam",
    "Ulloor",
    "Sreekariyam",
    "Poojappura",
    "Peroorkada"
  ],
  "kozhikode": [
    "Mavoor Road",
    "SM Street",
    "Palayam",
    "Nadakkavu",
    "Vellayil",
    "Chevayur",
    "Kallai",
    "Beypore"
  ],
  "thrissur": [
    "Swaraj Round",
    "MG Road",
    "East Fort",
    "West Fort",
    "Ayyanthole",
    "Ollur",
    "Puzhakkal"
  ],
  "kollam": [
    "Chinnakada",
    "Kadappakada",
    "Asramam",
    "Kavanad",
    "Polayathode",
    "Tangasseri"
  ],
  "alappuzha": [
    "Boat Jetty",
    "Mullakkal",
    "Civil Station",
    "Kalarcode",
    "Punnamada"
  ],
  "palakkad": [
    "Court Road",
    "TB Road",
    "Kanjikode Industrial Area",
    "Kalpathy",
    "Olavakkode"
  ],
  "kannur": [
    "Fort Road",
    "South Bazar",
    "Thana",
    "Payyambalam",
    "Burnacherry"
  ],
  "kottayam": [
    "Collectorate",
    "Nagampadam",
    "Baker Hill",
    "Kanjikuzhy",
    "Ettumanoor"
  ],
  "lucknow": [
    "Hazratganj",
    "Gomti Nagar",
    "Gomti Nagar Extension",
    "Aliganj",
    "Indira Nagar",
    "Mahanagar",
    "Alambagh",
    "Charbagh",
    "Aminabad",
    "Chowk",
    "Vikas Nagar",
    "Janki Puram",
    "Ashiyana",
    "Transport Nagar",
    "Rajajipuram",
    "Sarojini Nagar",
    "Amausi Industrial Area",
    "Chinhat"
  ],
  "kanpur": [
    "Civil Lines",
    "Swaroop Nagar",
    "Arya Nagar",
    "Gumti No 5",
    "Govind Nagar",
    "Fazalganj",
    "Panki Industrial Area",
    "Ratan Lal Nagar",
    "Kidwai Nagar",
    "Kakadeo",
    "Kalyanpur",
    "Mall Road"
  ],
  "agra": [
    "Sanjay Place",
    "Civil Lines",
    "Fatehabad Road",
    "Kamla Nagar",
    "Dayal Bagh",
    "Shahganj",
    "Bodla"
  ],
  "varanasi": [
    "Sigra",
    "Cantt",
    "Lanka",
    "Bhelupur",
    "Godowlia",
    "Lahurabir",
    "Shivpur",
    "Pandeypur",
    "Ramnagar"
  ],
  "prayagraj": [
    "Civil Lines",
    "Georgetown",
    "Tagore Town",
    "Katra",
    "Allahpur",
    "Naini Industrial Area",
    "Jhusi"
  ],
  "meerut": [
    " \u0936\u093e\u0938\u094d\u0924\u094d\u0930\u0940 Nagar",
    "Civil Lines",
    "Begum Bridge",
    "Abu Lane",
    "Partapur Industrial Area",
    "Modipuram"
  ],
  "bareilly": [
    "Civil Lines",
    "DD Puram",
    "Rajendra Nagar",
    "Clutterbuckganj",
    "Subhash Nagar",
    "Model Town"
  ],
  "aligarh": [
    "Center Point",
    "Civil Lines",
    "Marris Road",
    "Ramghat Road",
    "Tala Nagari Industrial Area"
  ],
  "moradabad": [
    "Civil Lines",
    "Ram Ganga Vihar",
    "Budh Bazaar",
    "Kanth Road",
    "Pakhbara"
  ],
  "gorakhpur": [
    "Golghar",
    "Civil Lines",
    "Betiahata",
    "GIDA Gorakhpur",
    "Medical College Road",
    "Mohaddipur"
  ],
  "saharanpur": [
    "Court Road",
    "Delhi Road",
    "Mission Compound",
    "Gill Colony",
    "Hasanpur"
  ],
  "jhansi": [
    "Civil Lines",
    "Sadar Bazar",
    "Elite Crossing",
    "Sipri Bazar",
    "Bijauli Industrial Area"
  ],
  "muzaffarnagar": [
    "New Mandi",
    "Civil Lines",
    "Bhapa Road",
    "Gandhi Colony",
    "Jansath Road"
  ],
  "mathura": [
    "Krishna Nagar",
    "Civil Lines",
    "Dampier Nagar",
    "Highway Plaza",
    "Vrindavan"
  ],
  "firozabad": [
    "Suhag Nagar",
    "Station Road",
    "Jalesar Road",
    "Asafabad",
    "Kotla Road"
  ],
  "dehradun": [
    "Rajpur Road",
    "Chakrata Road",
    "Paltan Bazaar",
    "Ballupur",
    "Vasant Vihar",
    "Dalanwala",
    "Patel Nagar",
    "ISBT Road",
    "Selaqui Industrial Area"
  ],
  "haridwar": [
    "Ranipur",
    "SIDCUL Haridwar",
    "Jwalapur",
    "Bhopatwala",
    "Kankhal",
    "Roshnabad"
  ],
  "roorkee": [
    "Civil Lines",
    "IIT Roorkee Campus",
    "Dehradun Road",
    "Haridwar Road",
    "Solani Puram"
  ],
  "haldwani": [
    "Nainital Road",
    "Kaladhungi Road",
    "Heera Nagar",
    "Mukherjee Nagar",
    "Bareilly Road"
  ],
  "jaipur": [
    "Malviya Nagar",
    "Vaishali Nagar",
    "C Scheme",
    "Mansarovar",
    "Raja Park",
    "Tonk Road",
    "MI Road",
    "Civil Lines",
    "Jagatpura",
    "Pratap Nagar",
    "Sodala",
    "Bani Park",
    "Ajmer Road",
    "Sitapura Industrial Area",
    "VKIA Vishwakarma",
    "Jhotwara",
    "Sanganer",
    "Vidhyadhar Nagar"
  ],
  "jodhpur": [
    "Ratanada",
    "Shastri Nagar",
    "Sardarpura",
    "Boronada SEZ",
    "Basni Industrial Area",
    "Mandore Road"
  ],
  "kota": [
    "Talwandi",
    "Vigyan Nagar",
    "Indraprastha Industrial Area",
    "DCM",
    "Gumanpura",
    "Dadabari"
  ],
  "bikaner": [
    "Rani Bazar",
    "Kote Gate",
    "Sadul Colony",
    "JNV Colony",
    "Bichhwal Industrial Area"
  ],
  "ajmer": [
    "Civil Lines",
    "Vaishali Nagar",
    "Panchsheel Nagar",
    "Kutchery Road",
    "Makhupura Industrial Area"
  ],
  "udaipur": [
    "Fatehpura",
    "Hiran Magri",
    "Sukher Industrial Area",
    "Madhuban",
    "Panchwati",
    "MIA Madri"
  ],
  "bhilwara": [
    "Bhopalganj",
    "Subhash Nagar",
    "Pur Road",
    "RIICO Growth Centre",
    "Textile City"
  ],
  "alwar": [
    "Matsya Industrial Area",
    "Scheme 2",
    "Moti Doongri",
    "Delhi Road",
    "Bhiwadi RIICO"
  ],
  "sikar": [
    "Fatehpur Road",
    "Station Road",
    "Piprali Road",
    "Silver Jubilee Road",
    "Bajaj Gram"
  ],
  "sri ganganagar": [
    "Purani Abadi",
    "Ridhiraj Vihar",
    "Sukhadia Circle",
    "Industrial Area"
  ],
  "indore": [
    "Vijay Nagar",
    "Palasia",
    "Old Palasia",
    "New Palasia",
    "MG Road",
    "AB Road",
    "Sapna Sangeeta",
    "Bhawarkua",
    "Rajwada",
    "Khandwa Road",
    "Geeta Bhawan",
    "Annapurna Road",
    "Rau",
    "Pithampur Industrial Area",
    "Sanwer Road Industrial Area",
    "Bicholi Mardana",
    "Nipania",
    "Mahalaxmi Nagar"
  ],
  "bhopal": [
    "MP Nagar Zone 1",
    "MP Nagar Zone 2",
    "Arera Colony",
    "Shahpura",
    "Habibganj",
    "New Market",
    "Kolar Road",
    "Hoshangabad Road",
    "Govindpura Industrial Area",
    "Mandideep Industrial Area",
    "Bairagarh"
  ],
  "jabalpur": [
    "Civil Lines",
    "Napier Town",
    "Wright Town",
    "Gorakhpur",
    "Vijay Nagar",
    "Adhartal",
    "Richhai"
  ],
  "gwalior": [
    "City Centre",
    "Lashkar",
    "Morar",
    "Maharaj Bada",
    "Malviya Nagar",
    "Malanpur Industrial Area"
  ],
  "ujjain": [
    "Freeganj",
    "Dewas Road",
    "Madhav Nagar",
    "Nanakheda",
    "Maksi Road Industrial Area"
  ],
  "sagar": [
    "Civil Lines",
    "Makronia",
    "Gopal Ganj",
    "Katra Bazar",
    "Tilli"
  ],
  "dewas": [
    "BNP Road",
    "Vikas Nagar",
    "Industrial Area Phase 1",
    "Industrial Area Phase 2",
    "Ujjain Road"
  ],
  "satna": [
    "Civil Lines",
    "Panna Road",
    "Rewa Road",
    "Bharhut Nagar",
    "Industrial Area"
  ],
  "ratlam": [
    "Station Road",
    "Do Batti",
    "Kasturba Nagar",
    "Alkapuri",
    "Industrial Area"
  ],
  "rewa": [
    "Civil Lines",
    "Bodabag",
    "University Road",
    "Kothi Compound",
    "Sirmour Road"
  ],
  "raipur": [
    "Pandri",
    "Telibandha",
    "VIP Road",
    "Shankar Nagar",
    "Devendra Nagar",
    "Samta Colony",
    "Civil Lines",
    "Fafadih",
    "Urla Industrial Area",
    "Bhanpuri",
    "Siltara",
    "Naya Raipur"
  ],
  "bhilai": [
    "Sector 1",
    "Sector 6",
    "Sector 10",
    "Nehru Nagar",
    "Supela",
    "Power House",
    "Durg",
    "Borai Industrial Area"
  ],
  "bilaspur": [
    "Vyapar Vihar",
    "Civil Lines",
    "Link Road",
    "Rajkishore Nagar",
    "Sirgitti Industrial Area",
    "Tifra"
  ],
  "korba": [
    "NTPC Township",
    "BALCO Township",
    "Transport Nagar",
    "Power Grid",
    "CSEB Colony"
  ],
  "patna": [
    "Boring Road",
    "Boring Canal Road",
    "Bailey Road",
    "Kankarbagh",
    "Rajendra Nagar",
    "Patliputra Colony",
    "Anisabad",
    "Fraser Road",
    "Exhibition Road",
    "Gandhi Maidan",
    "Danapur",
    "Phulwari Sharif",
    "Fatuha Industrial Area"
  ],
  "gaya": [
    "Civil Lines",
    "AP Colony",
    "Rampur",
    "Bodhgaya Road",
    "Chandauti",
    "GB Road"
  ],
  "bhagalpur": [
    "Adampur",
    "Tilkamanjhi",
    "Zero Mile",
    "Barari",
    "Station Road",
    "Aliganj"
  ],
  "muzaffarpur": [
    "Mithanpura",
    "Brahmpura",
    "Kalyani",
    "Motijheel",
    "Akharghat",
    "Bela Industrial Area"
  ],
  "darbhanga": [
    "Laheriasarai",
    "Tower Chowk",
    "Benta",
    "Donar",
    "Allpatti"
  ],
  "purnia": [
    "Line Bazar",
    "Navratan Hatta",
    "Bhatta Bazar",
    "Gulabbagh",
    "Rambagh"
  ],
  "bihar sharif": [
    "Hospital Mor",
    "Khandakpar",
    "Ranchi Road",
    "Ramchandrapur",
    "Sohsarai"
  ],
  "ranchi": [
    "Main Road",
    "Lalpur",
    "Doranda",
    "Hinoo",
    "Harmu Housing Colony",
    "Ashok Nagar",
    "Bariatu",
    "Kanke Road",
    "Ratu Road",
    "Namkum Industrial Area",
    "Tupudana Industrial Area",
    "Dhurwa"
  ],
  "jamshedpur": [
    "Bistupur",
    "Sakchi",
    "Kadma",
    "Sonari",
    "Telco Colony",
    "Golmuri",
    "Adityapur Industrial Area",
    "Gamharia",
    "Baridih",
    "Jugsalai",
    "Mango",
    "Sidgora"
  ],
  "dhanbad": [
    "Bank More",
    "Saraidhela",
    "Hirapur",
    "Steel Gate",
    "Dhaiya",
    "Govindpur",
    "Katras",
    "Jharia"
  ],
  "bokaro": [
    "City Centre Sector 4",
    "Sector 1",
    "Sector 9",
    "Chas",
    "Co-operative Colony",
    "Bokaro Industrial Area"
  ],
  "deoghar": [
    "Castairs Town",
    "Bilasi Town",
    "Williams Town",
    "Jasidih Industrial Area",
    "VIP Chowk"
  ],
  "bhubaneswar": [
    "Saheed Nagar",
    "Nayapalli",
    "Jayadev Vihar",
    "Chandrasekharpur",
    "Patia",
    "Khandagiri",
    "Bapuji Nagar",
    "Janpath",
    "Master Canteen",
    "Rasulgarh",
    "Mancheswar Industrial Estate",
    "Infocity",
    "Baramunda",
    "Old Town",
    "Laxmisagar",
    "Tamando",
    "Ghatikia"
  ],
  "cuttack": [
    "Badambadi",
    "College Square",
    "Mangalabag",
    "Madhupatna",
    "Choudwar",
    "Jagatpur Industrial Estate",
    "Link Road"
  ],
  "rourkela": [
    "Civil Township",
    "Sector 4",
    "Sector 19",
    "Uditnagar",
    "Panposh",
    "Kalunga Industrial Estate",
    "Main Road"
  ],
  "berhampur": [
    "Gandhi Nagar",
    "Gosaninuagaon",
    "Kamapalli",
    "Engineering School Road",
    "Courtpeta"
  ],
  "sambalpur": [
    "Budharaja",
    "Ainthapali",
    "Dhanupali",
    "Khetrajpur",
    "Modipara",
    "Burla"
  ],
  "chandigarh": [
    "Sector 17",
    "Sector 35",
    "Sector 22",
    "Sector 8",
    "Sector 9",
    "Sector 26",
    "Sector 34",
    "Industrial Area Phase 1",
    "Industrial Area Phase 2",
    "Sector 43",
    "Sector 70 Mohali",
    "Phase 7 Mohali",
    "Phase 8 Industrial Area Mohali",
    "Phase 9 Mohali",
    "Sector 82 Mohali",
    "Sector 5 Panchkula",
    "Sector 11 Panchkula",
    "Industrial Area Phase 1 Panchkula",
    "Mani Majra",
    "Zirakpur"
  ],
  "ludhiana": [
    "Model Town",
    "Sarabha Nagar",
    "Ferozepur Road",
    "Civil Lines",
    "Ghumar Mandi",
    "BRS Nagar",
    "Focal Point",
    "Dhandari Kalan",
    "Gill Road",
    "Sundar Nagar",
    "Pakhowal Road",
    "Moti Nagar"
  ],
  "amritsar": [
    "Mall Road",
    "Ranjit Avenue",
    "Civil Lines",
    "Lawrence Road",
    "GT Road",
    "Majitha Road",
    "Chheharta"
  ],
  "jalandhar": [
    "Model Town",
    "Civil Lines",
    "GT Road",
    "Nakodar Road",
    "Cantt",
    "Focal Point",
    "Rama Mandi"
  ],
  "patiala": [
    "Leela Bhawan",
    "Model Town",
    "Urban Estate Phase 1",
    "Urban Estate Phase 2",
    "Baradari",
    "Focal Point"
  ],
  "bathinda": [
    "Civil Lines",
    "Mall Road",
    "Model Town Phase 1",
    "Model Town Phase 2",
    "GT Road",
    "Growth Centre"
  ],
  "panipat": [
    "Sanjay Chowk",
    "Model Town",
    "GT Road",
    "Sector 11",
    "Sector 12",
    "Sector 25 Industrial Area",
    "Refinery"
  ],
  "karnal": [
    "Model Town",
    "Sector 12",
    "Sector 13",
    "Civil Lines",
    "GT Road",
    "Sector 3 Industrial Area"
  ],
  "rohtak": [
    "Model Town",
    "Civil Lines",
    "Delhi Road",
    "Sector 1",
    "Sector 2",
    "IMT Rohtak"
  ],
  "hisar": [
    "Urban Estate 2",
    "Model Town",
    "Delhi Road",
    "Auto Market",
    "Industrial Area"
  ],
  "ambala": [
    "Ambala Cantt",
    "Ambala City",
    "Model Town",
    "Sadar Bazar",
    "Twin City Industrial Area"
  ],
  "sonipat": [
    "Sector 14",
    "Sector 15",
    "Model Town",
    "Murthal Road",
    "Kundli Industrial Area",
    "Rai IMT"
  ],
  "siliguri": [
    "Sevoke Road",
    "Hill Cart Road",
    "Pradhan Nagar",
    "Hakim Para",
    "Matigara",
    "Khalpara",
    "Bidhan Market"
  ],
  "asansol": [
    "GT Road",
    "Burnpur",
    "Ushagram",
    "Chelidanga",
    "Murgasol",
    "Kalyanpur Housing"
  ],
  "durgapur": [
    "City Centre",
    "Benachity",
    "Bidhannagar",
    "Steel Township",
    "Muchipara",
    "Durgapur Industrial Area"
  ],
  "guwahati": [
    "GS Road",
    "Christian Basti",
    "Dispur",
    "Paltan Bazaar",
    "Pan Bazaar",
    "Ganeshguri",
    "Zoo Road",
    "Ulubari",
    "Six Mile",
    "Beltola",
    "Bhangagarh",
    "Chandmari",
    "Jalukbari",
    "Bamunimaidan Industrial Area"
  ],
  "shillong": [
    "Police Bazar",
    "Laitumkhrah",
    "Barabazar",
    "Labir",
    "Nongthymmai",
    "Mawlai"
  ],
  "agartala": [
    "Banamalipur",
    "Melarmath",
    "Akhaura Road",
    "Radhanagar",
    "Indranagar",
    "Bodhjungnagar"
  ],
  "imphal": [
    "Thangal Bazar",
    "Paona Bazar",
    "Kangla",
    "Babupara",
    "Lamphelpat"
  ],
  "aizawl": [
    "Zarkawt",
    "Bawngkawn",
    "Chanmari",
    "Khatla",
    "Dinthar"
  ],
  "gangtok": [
    "MG Marg",
    "Deorali",
    "Tadong",
    "Ranipool",
    "Development Area"
  ],
  "goa": [
    "Panaji",
    "Margao",
    "Vasco da Gama",
    "Mapusa",
    "Ponda",
    "Porvorim",
    "Calangute",
    "Candolim",
    "Verna Industrial Estate",
    "Kundaim MIDC"
  ],
  "shimla": [
    "The Mall",
    "Lakkar Bazar",
    "Sanjauli",
    "Chotta Shimla",
    "Kasumpti",
    "Boileauganj",
    "New Shimla"
  ],
  "dharamshala": [
    "Kotwali Bazar",
    "McLeod Ganj",
    "Civil Lines",
    "Dharamsala Cantt",
    "Kachhari"
  ],
  "baddi": [
    "Baddi Industrial Area",
    "Barotiwala",
    "Nalagarh",
    "Sai Road",
    "Housing Board"
  ],
  "srinagar": [
    "Lal Chowk",
    "Rajbagh",
    "Karan Nagar",
    "Hyderpora",
    "Batmaloo",
    "Sanat Nagar",
    "Soura"
  ],
  "jammu": [
    "Gandhi Nagar",
    "Trikuta Nagar",
    "Bahu Plaza",
    "Channi Himmat",
    "Bari Brahmana Industrial Area",
    "Jewel Chowk"
  ]
};

export const CITY_ALIASES = {
  "bengaluru": "bangalore",
  "blr": "bangalore",
  "bombay": "mumbai",
  "bom": "mumbai",
  "greater mumbai": "mumbai",
  "navi-mumbai": "navi mumbai",
  "calcutta": "kolkata",
  "ccu": "kolkata",
  "madras": "chennai",
  "maa": "chennai",
  "gurugram": "gurgaon",
  "ggn": "gurgaon",
  "ncr": "delhi",
  "dilli": "delhi",
  "new delhi": "delhi",
  "greater noida": "noida",
  "secunderabad": "hyderabad",
  "hyd": "hyderabad",
  "cyberabad": "hyderabad",
  "poona": "pune",
  "pimpri": "pune",
  "chinchwad": "pune",
  "pimpri chinchwad": "pune",
  "pcmc": "pune",
  "amdavad": "ahmedabad",
  "cochin": "kochi",
  "ernakulam": "kochi",
  "trivandrum": "thiruvananthapuram",
  "calicut": "kozhikode",
  "vizag": "visakhapatnam",
  "waltair": "visakhapatnam",
  "bezawada": "vijayawada",
  "baroda": "vadodara",
  "trichy": "trichy",
  "tiruchirappalli": "trichy",
  "tiruchirapalli": "trichy",
  "allahabad": "prayagraj",
  "banaras": "varanasi",
  "kashi": "varanasi",
  "chhatrapati sambhaji nagar": "aurangabad",
  "sambhajinagar": "aurangabad",
  "dharashiv": "osmanabad",
  "belagavi": "belgaum",
  "kalaburagi": "gulbarga",
  "vijayapura": "bijapur",
  "shivamogga": "shimoga",
  "tumakuru": "tumkur",
  "ballari": "bellary",
  "mysuru": "mysore",
  "dharwad": "hubli",
  "hubli-dharwad": "hubli",
  "panaji": "goa",
  "north goa": "goa",
  "south goa": "goa",
  "vasco": "goa",
  "vasco-da-gama": "goa",
  "sas nagar": "chandigarh",
  "mohali": "chandigarh",
  "panchkula": "chandigarh",
  "bbsr": "bhubaneswar",
  "orissa": "bhubaneswar",
  "pondicherry": "puducherry",
  "tanjore": "thanjavur",
  "alleppey": "alappuzha",
  "palghat": "palakkad",
  "cannanore": "kannur",
  "quilon": "kollam",
  "moradabad brass": "moradabad",
  "bhiwadi": "alwar",
  "pithampur": "indore",
  "mandideep": "bhopal",
  "adityapur": "jamshedpur",
  "durg-bhilai": "bhilai",
  "durg": "bhilai",
  "manesar": "gurgaon",
  "kundli": "sonipat",
  "baddi barotiwala": "baddi",
  "mcleodganj": "dharamshala"
};

const DEFAULT_AREAS = [
  "Central",
  "North",
  "South",
  "East",
  "West",
  "Main Market",
  "Station Road",
  "Civil Lines",
  "Model Town",
  "City Center",
  "Commercial Complex",
  "Industrial Area",
  "MIDC",
  "GIDC",
  "RIICO",
  "Bazaar",
  "Ring Road",
  "Court Road",
  "College Road",
  "Bus Stand Road"
];

/**
 * Returns canonical list of major localities for a given normalized city.
 * Used as a fallback provider when dynamic locality discovery is unseeded or exhausted.
 */
export function getCityAreas(city) {
  if (!city) return DEFAULT_AREAS;
  const key = String(city).trim().toLowerCase().replace(/[-_]+/g, ' ');
  
  // 1. Direct match
  if (CITY_AREAS[key]) {
    return CITY_AREAS[key];
  }
  
  // 2. Direct alias match
  if (CITY_ALIASES[key] && CITY_AREAS[CITY_ALIASES[key]]) {
    return CITY_AREAS[CITY_ALIASES[key]];
  }

  // 3. Substring / fuzzy match against known cities and aliases
  for (const [cityName, areas] of Object.entries(CITY_AREAS)) {
    if (key.includes(cityName) || cityName.includes(key)) {
      return areas;
    }
  }

  for (const [aliasName, targetCity] of Object.entries(CITY_ALIASES)) {
    if (key.includes(aliasName) || aliasName.includes(key)) {
      if (CITY_AREAS[targetCity]) {
        return CITY_AREAS[targetCity];
      }
    }
  }

  return DEFAULT_AREAS;
}
