// Canonical Top Localities, Wards & Industrial Hubs for Indian Metropolitan & Tier-2 Cities
// Enables exhaustive multi-area search across Justdial, Sulekha, Grotal, IndiaMART, TradeIndia
// Compiled from municipal corporation ward master plans, census urban agglomerations, and Wikipedia.

export const CITY_AREAS = {
  "delhi": [
    "Connaught Place",
    "Karol Bagh",
    "Lajpat Nagar",
    "South Extension",
    "Rohini",
    "Pitampura",
    "Dwarka",
    "Janakpuri",
    "Saket",
    "Hauz Khas",
    "Greater Kailash",
    "Vasant Kunj",
    "Nehru Place",
    "Laxmi Nagar",
    "Preet Vihar",
    "Chandni Chowk",
    "Rajouri Garden",
    "Punjabi Bagh",
    "Paschim Vihar",
    "Shahdara",
    "Malviya Nagar",
    "Defence Colony",
    "Mayur Vihar",
    "Okhla",
    "Patel Nagar",
    "Kalkaji",
    "Green Park",
    "Model Town",
    "Shalimar Bagh",
    "Tilak Nagar",
    "Mayapuri",
    "Wazirpur",
    "Naraina",
    "Bawana",
    "Kirti Nagar",
    "Vasant Vihar",
    "Safdarjung Enclave",
    "CR Park",
    "Alaknanda",
    "Paharganj",
    "Daryaganj",
    "Civil Lines",
    "Ashok Vihar",
    "Kamla Nagar",
    "GTB Nagar",
    "Nirman Vihar",
    "Vivek Vihar",
    "Patparganj",
    "Anand Vihar",
    "Vikaspuri",
    "Uttam Nagar",
    "Subhash Nagar",
    "Narela",
    "Mangolpuri",
    "Kashmere Gate",
    "Chanakyapuri",
    "Barakhamba Road",
    "Jor Bagh",
    "Sundar Nagar",
    "New Friends Colony"
  ],
  "gurgaon": [
    "DLF Cyber City",
    "DLF Phase 1",
    "DLF Phase 2",
    "DLF Phase 3",
    "DLF Phase 4",
    "DLF Phase 5",
    "Golf Course Road",
    "Golf Course Extension",
    "Sohna Road",
    "MG Road",
    "Sector 29",
    "Sector 14",
    "Sector 15",
    "Sector 49",
    "Sector 56",
    "Sector 57",
    "Sector 82",
    "Sector 83",
    "Manesar",
    "Udyog Vihar",
    "Palam Vihar",
    "Sushant Lok",
    "South City 1",
    "South City 2",
    "Nirvana Country",
    "Sector 48",
    "Sector 50",
    "Sector 65",
    "Sector 67",
    "Sector 70",
    "Sector 84",
    "Sector 89",
    "Sector 92",
    "New Gurgaon",
    "Old Gurgaon"
  ],
  "noida": [
    "Sector 18",
    "Sector 62",
    "Sector 63",
    "Sector 15",
    "Sector 16",
    "Sector 50",
    "Sector 76",
    "Sector 128",
    "Sector 137",
    "Sector 150",
    "Sector 1",
    "Sector 2",
    "Sector 3",
    "Sector 10",
    "Sector 12",
    "Sector 27",
    "Sector 29",
    "Sector 34",
    "Sector 51",
    "Sector 52",
    "Sector 74",
    "Sector 75",
    "Sector 78",
    "Sector 104",
    "Sector 110",
    "Sector 135",
    "Sector 142",
    "Noida Extension",
    "Greater Noida West",
    "Pari Chowk",
    "Knowledge Park",
    "Surajpur",
    "Kasna",
    "Omega",
    "Alpha"
  ],
  "ghaziabad": [
    "Indirapuram",
    "Vaishali",
    "Kaushambi",
    "Vasundhara",
    "Raj Nagar",
    "Raj Nagar Extension",
    "Crossings Republik",
    "Sahibabad",
    "Mohan Nagar",
    "Kavi Nagar",
    "Loni",
    "Sanjay Nagar",
    "Nehru Nagar",
    "Shalimar Garden",
    "Patel Nagar",
    "Surya Nagar",
    "Chander Nagar",
    "Bhopura",
    "Vijay Nagar",
    "Govindpuram"
  ],
  "faridabad": [
    "Sector 15",
    "Sector 16",
    "Sector 21",
    "Sector 28",
    "Sector 31",
    "NIT Faridabad",
    "Ballabhgarh",
    "Neharpar",
    "Greater Faridabad",
    "Surajkund",
    "Mathura Road",
    "Sector 7",
    "Sector 8",
    "Sector 9",
    "Sector 10",
    "Sector 11",
    "Sector 14",
    "Sector 19",
    "Sector 37",
    "Sector 85",
    "Industrial Area",
    "Old Faridabad",
    "Bata Chowk",
    "Neelam Chowk",
    "Badkhal"
  ],
  "mumbai": [
    "Andheri West",
    "Andheri East",
    "Bandra West",
    "Bandra East",
    "Borivali West",
    "Borivali East",
    "Malad West",
    "Malad East",
    "Kandivali West",
    "Kandivali East",
    "Goregaon West",
    "Goregaon East",
    "Juhu",
    "Santacruz West",
    "Santacruz East",
    "Khar West",
    "Khar East",
    "Vile Parle West",
    "Vile Parle East",
    "Jogeshwari",
    "Powai",
    "Ghatkopar West",
    "Ghatkopar East",
    "Mulund West",
    "Mulund East",
    "Bhandup",
    "Vikhroli",
    "Kanjurmarg",
    "Kurla West",
    "Kurla East",
    "Chembur",
    "Govandi",
    "Mankhurd",
    "Dadar West",
    "Dadar East",
    "Worli",
    "Lower Parel",
    "Prabhadevi",
    "Parel",
    "Mahim",
    "Matunga",
    "Wadala",
    "Sion",
    "Colaba",
    "Cuffe Parade",
    "Nariman Point",
    "Fort",
    "Churchgate",
    "Marine Lines",
    "Girgaon",
    "Tardeo",
    "Breach Candy",
    "Malabar Hill",
    "Byculla",
    "Dahisar",
    "Mira Road",
    "Bhayandar",
    "Thane West",
    "Navi Mumbai",
    "Panvel"
  ],
  "thane": [
    "Thane West",
    "Thane East",
    "Ghodbunder Road",
    "Majiwada",
    "Vartak Nagar",
    "Naupada",
    "Panch Pakhadi",
    "Hiranandani Estate",
    "Hiranandani Meadows",
    "Wagle Estate",
    "Kasarvadavali",
    "Manpada",
    "Kolshet Road",
    "Balkum",
    "Kalwa",
    "Mumbra",
    "Diva",
    "Kopri",
    "Waghbil",
    "Ovala",
    "Anand Nagar",
    "Kapurbawdi",
    "Brahmand",
    "Louiswadi",
    "Khopat"
  ],
  "navi mumbai": [
    "Vashi",
    "Nerul",
    "Belapur",
    "Kharghar",
    "Sanpada",
    "Airoli",
    "Kopar Khairane",
    "Ghansoli",
    "Seawoods",
    "Ulwe",
    "Dronagiri",
    "Taloja",
    "Turbhe",
    "Rabale",
    "Mahape",
    "Juinagar",
    "Kamothe",
    "Kalamboli",
    "CBD Belapur",
    "MIDC Industrial Area"
  ],
  "pune": [
    "Kothrud",
    "Viman Nagar",
    "Baner",
    "Wakad",
    "Hinjawadi",
    "Koregaon Park",
    "Kalyani Nagar",
    "Aundh",
    "Hadapsar",
    "Pimpri",
    "Chinchwad",
    "Magarpatta",
    "Shivaji Nagar",
    "Camp",
    "Bibwewadi",
    "Sinhagad Road",
    "Kharadi",
    "Bavdhan",
    "Wanowrie",
    "Vishrantwadi",
    "Dhanori",
    "Pimple Saudagar",
    "Nigdi",
    "Bhosari",
    "Katraj",
    "Chakan",
    "Talawade",
    "Balewadi",
    "Mahalunge",
    "Sus",
    "Karve Nagar",
    "Erandwane",
    "Deccan Gymkhana",
    "FC Road",
    "JM Road",
    "Wadgaon Sheri",
    "Yerawada",
    "Lohegaon",
    "Wagholi",
    "Amanora",
    "Mundhwa",
    "Fatimanagar",
    "Kondhwa",
    "NIBM Road",
    "Undri",
    "Dhankawadi",
    "Sahakar Nagar",
    "Swargate",
    "Dhanyari",
    "Warje",
    "Pashan",
    "Akurdi",
    "Ravet",
    "Punawale",
    "Tathawade"
  ],
  "nagpur": [
    "Dharampeth",
    "Ramdaspeth",
    "Dhantoli",
    "Sitabuldi",
    "Sadar",
    "Civil Lines",
    "Shankar Nagar",
    "Bajaj Nagar",
    "Pratap Nagar",
    "Laxmi Nagar",
    "Wardha Road",
    "Hingna",
    "MIDC Hingna",
    "Butibori",
    "Trimurti Nagar",
    "Manish Nagar",
    "Besa",
    "Nandanvan",
    "Mahal",
    "Itwari",
    "Gandhibagh",
    "Jaripatka",
    "Koradi Road",
    "Wadi",
    "Khamla"
  ],
  "nashik": [
    "College Road",
    "Gangapur Road",
    "Mahatma Nagar",
    "Indira Nagar",
    "Govind Nagar",
    "Mumbai Naka",
    "Panchavati",
    "Dwarka",
    "Cidco",
    "Satpur",
    "Ambad MIDC",
    "Deolali",
    "Nashik Road",
    "Pathardi Phata",
    "Adgaon",
    "Jail Road",
    "Ashok Nagar",
    "Canada Corner",
    "Sharanpur Road",
    "Untwadi"
  ],
  "aurangabad": [
    "Cidco",
    "Waluj MIDC",
    "Shendra MIDC",
    "Jalna Road",
    "Kranti Chowk",
    "Cannaught Place",
    "Garkheda",
    "Beed Bypass",
    "Chikalthana",
    "Samarth Nagar",
    "Nirala Bazar",
    "Osmanpura",
    "Shahgunj",
    "Railway Station Road",
    "Padampura"
  ],
  "kolhapur": [
    "Rajarampuri",
    "Shahupuri",
    "Tarabai Park",
    "Laxmipuri",
    "Nagala Park",
    "Kasba Bawada",
    "Shiroli MIDC",
    "Gokul Shirgaon",
    "Rankala",
    "Rajaramshet",
    "Station Road",
    "Mahadwar Road",
    "Kadamwadi",
    "Ruikar Colony",
    "Mangalwar Peth"
  ],
  "solapur": [
    "Jule Solapur",
    "Hotgi Road",
    "Saat Rasta",
    "Old Ausa Road",
    "Navi Peth",
    "MIDC Solapur",
    "Ashok Chowk",
    "Lashkar",
    "Railway Lines",
    "Bhavani Peth"
  ],
  "goa": [
    "Panaji",
    "Margao",
    "Vasco da Gama",
    "Mapusa",
    "Ponda",
    "Porvorim",
    "Calangute",
    "Candolim",
    "Baga",
    "Anjuna",
    "Colva",
    "Benaulim",
    "Verna Industrial Estate",
    "Kundaim",
    "Tivim"
  ],
  "bangalore": [
    "Koramangala",
    "Indiranagar",
    "Whitefield",
    "HSR Layout",
    "Jayanagar",
    "JP Nagar",
    "Electronic City",
    "Marathahalli",
    "BTM Layout",
    "Hebbal",
    "Malleshwaram",
    "Banashankari",
    "Rajajinagar",
    "Yelahanka",
    "Bellandur",
    "Sarjapur Road",
    "Kalyan Nagar",
    "Vijayanagar",
    "Basavanagudi",
    "RT Nagar",
    "Richmond Town",
    "Domlur",
    "Ulsoor",
    "Frazer Town",
    "Bannerghatta Road",
    "Harlur",
    "Kasavanahalli",
    "Kengeri",
    "KR Puram",
    "Mahadevapura",
    "Vidyaranyapura",
    "Thanisandra",
    "Begur",
    "Bommanahalli",
    "Nagarbhavi",
    "Peenya",
    "Bommasandra",
    "Jigani",
    "Bidadi",
    "Kadugodi",
    "Hoodi",
    "Varthur",
    "CV Raman Nagar",
    "Kammanahalli",
    "HRBR Layout",
    "Hennur",
    "Sahakara Nagar",
    "Sanjaynagar",
    "Mathikere",
    "Yeshwanthpur",
    "Basaveshwaranagar",
    "Rajarajeshwari Nagar",
    "Padmanabhanagar",
    "Uttarahalli",
    "Gottigere"
  ],
  "mysore": [
    "Gokulam",
    "Vijayanagar",
    "Jayalakshmipuram",
    "Saraswathipuram",
    "Kuvempunagar",
    "Hebbal Industrial Area",
    "Belagola",
    "Yadavagiri",
    "Siddhartha Layout",
    "Chamundipuram",
    "Nazarbad",
    "Bannimantap",
    "VV Mohalla",
    "Ramakrishnanagar",
    "Dattagalli",
    "JP Nagar",
    "Metagalli",
    "Alanahalli",
    "Bogadi",
    "Hootagalli"
  ],
  "mangalore": [
    "Hampankatta",
    "Kadri",
    "Bejai",
    "Lalbagh",
    "Balmatta",
    "Falnir",
    "Bendoorwell",
    "Kankanady",
    "Attavar",
    "Mannagudda",
    "Derebail",
    "Kavoor",
    "Surathkal",
    "Baikampady",
    "Panambur",
    "Urwa",
    "Kottara Chowki",
    "Yeyyadi",
    "Bondel",
    "Padil"
  ],
  "hubli": [
    "Vidyanagar",
    "Gokul Road",
    "Keshwapur",
    "Deshpande Nagar",
    "Shirur Park",
    "Navanagar",
    "Tarihal",
    "Rayapur",
    "Sattur",
    "Dharwad",
    "Malmaddi",
    "Gandhinagar",
    "Unkal",
    "Bengeri",
    "Hosur"
  ],
  "belgaum": [
    "Tilakwadi",
    "Camp",
    "Hindwadi",
    "Vadgaon",
    "Shahapur",
    "Udyambag",
    "Macche",
    "Auto Nagar",
    "Channamma Nagar",
    "Angol",
    "Khasbag",
    "Mandoli Road",
    "Bhagya Nagar",
    "Peeranwadi",
    "Rani Chennamma Nagar"
  ],
  "hyderabad": [
    "Kukatpally",
    "Banjara Hills",
    "Jubilee Hills",
    "Secunderabad",
    "Madhapur",
    "Gachibowli",
    "Begumpet",
    "Ameerpet",
    "Dilsukhnagar",
    "LB Nagar",
    "Miyapur",
    "Nizampet",
    "Manikonda",
    "Uppal",
    "Kondapur",
    "Attapur",
    "Tarnaka",
    "Alwal",
    "Sainikpuri",
    "Chanda Nagar",
    "Hitech City",
    "Somajiguda",
    "Malakpet",
    "Mehdipatnam",
    "Abids",
    "Himayat Nagar",
    "Kothapet",
    "Nagole",
    "Bowenpally",
    "Kompally",
    "Nampally",
    "Saidabad",
    "Masab Tank",
    "Sanjeeva Reddy Nagar",
    "Moosapet",
    "Hayath Nagar",
    "Safilguda",
    "ECIL",
    "Malkajgiri",
    "Tolichowki",
    "Charminar",
    "Kacheguda",
    "Lingampally",
    "Shamshabad",
    "Rajendra Nagar",
    "AS Rao Nagar",
    "Nallagandla",
    "Tellapur",
    "Bachupally",
    "Hafeezpet",
    "Jeedimetla",
    "Balanagar",
    "Sanathnagar",
    "Cherlapally",
    "Nacharam",
    "Kattedan",
    "Patancheru",
    "Medchal",
    "Kothaguda",
    "Kokapet",
    "Narsingi",
    "Film Nagar",
    "Yousufguda",
    "Pragathi Nagar",
    "Beeramguda",
    "Vanasthalipuram",
    "Karmanghat",
    "Saroornagar",
    "Champapet",
    "Habsiguda"
  ],
  "visakhapatnam": [
    "MVP Colony",
    "Gajuwaka",
    "Madhurawada",
    "Dwaraka Nagar",
    "Siripuram",
    "Asilmetta",
    "Jagadamba Junction",
    "Seethammadhara",
    "Rushikonda",
    "Kurmannapalem",
    "Pedda Waltair",
    "Lawsons Bay Colony",
    "Ram Nagar",
    "Akkayyapalem",
    "Kancharapalem",
    "Pendurthi",
    "Gopalapatnam",
    "Simhachalam",
    "Marripalem",
    "NAD Junction",
    "Steel Plant Township",
    "Autonagar",
    "Sheela Nagar",
    "Bheemunipatnam",
    "Yendada"
  ],
  "vijayawada": [
    "Benz Circle",
    "MG Road",
    "Governorpet",
    "Suryaraopet",
    "Satyanarayanapuram",
    "Patamata",
    "Auto Nagar",
    "Moghalrajpuram",
    "Bhavanipuram",
    "Labbipet",
    "Gunadala",
    "Enikepadu",
    "Gannavaram",
    "Poranki",
    "Penamaluru",
    "Gollapudi",
    "One Town",
    "Kankipadu",
    "Kanuru",
    "Payakapuram"
  ],
  "guntur": [
    "Brodipet",
    "Arundelpet",
    "Lakshmipuram",
    "Kothapet",
    "Pattabhipuram",
    "Amaravathi Road",
    "Auto Nagar",
    "Vidya Nagar",
    "Shyamala Nagar",
    "Gujjanagundla",
    "Nallapadu",
    "Brindavan Gardens",
    "Gorantla",
    "Old Guntur",
    "Santhi Nagar"
  ],
  "tirupati": [
    "Korlagunta",
    "Bhavani Nagar",
    "Balaji Colony",
    "AIR Bypass Road",
    "Renigunta",
    "Karakambadi Road",
    "MR Palli",
    "Leela Mahal Circle",
    "Chandragiri",
    "Settipalli",
    "Alipiri",
    "Tiruchanur",
    "Mangalam",
    "Padmavathi Nagar",
    "Bairagi Patteda"
  ],
  "chennai": [
    "T Nagar",
    "Anna Nagar",
    "Velachery",
    "Adyar",
    "Mylapore",
    "Nungambakkam",
    "Guindy",
    "Porur",
    "Tambaram",
    "Thiruvanmiyur",
    "Besant Nagar",
    "Kodambakkam",
    "Alwarpet",
    "Kilpauk",
    "Royapettah",
    "Chromepet",
    "Vadapalani",
    "Perambur",
    "Sholinganallur",
    "OMR",
    "Medavakkam",
    "Pallavaram",
    "Ashok Nagar",
    "Mogappair",
    "Kolathur",
    "Ambattur",
    "Avadi",
    "Poonamallee",
    "Sriperumbudur",
    "Egmore",
    "Gopalapuram",
    "Triplicane",
    "Sowcarpet",
    "George Town",
    "Tondiarpet",
    "Villivakkam",
    "Valasaravakkam",
    "Ramapuram",
    "Virugambakkam",
    "West Mambalam",
    "Saidapet",
    "Kotturpuram",
    "RA Puram",
    "Mandaveli",
    "Kottivakkam",
    "Palavakkam",
    "Neelankarai",
    "Perungudi",
    "Thoraipakkam",
    "Madipakkam",
    "Pallikaranai",
    "Nanganallur",
    "Selaiyur",
    "Chitlapakkam",
    "Perungalathur"
  ],
  "coimbatore": [
    "RS Puram",
    "Gandhipuram",
    "Peelamedu",
    "Saibaba Colony",
    "Saravanampatti",
    "Ramanathapuram",
    "Singanallur",
    "Ganapathy",
    "Town Hall",
    "Race Course",
    "Vadavalli",
    "Thudiyalur",
    "Kovaipudur",
    "Kuniyamuthur",
    "Ukkadam",
    "Sundarapuram",
    "Kurichi",
    "Eachanari",
    "Sulur",
    "Ondipudur",
    "Hope College",
    "Kalapatti",
    "Neelambur",
    "Vilankurichi",
    "Perur"
  ],
  "madurai": [
    "Anna Nagar",
    "KK Nagar",
    "Simmakkal",
    "Goripalayam",
    "Tallakulam",
    "Mattuthavani",
    "Sellur",
    "Villapuram",
    "Teppakulam",
    "Pasumalai",
    "Thirunagar",
    "Bye Pass Road",
    "SS Colony",
    "Arappalayam",
    "Mahaboobpalem",
    "Palanganatham",
    "Kochadai",
    "Koodal Nagar",
    "Othakadai",
    "Iyer Bungalow"
  ],
  "trichy": [
    "Thillai Nagar",
    "Cantonment",
    "KK Nagar",
    "Srirangam",
    "Woraiyur",
    "Golden Rock",
    "Palakkarai",
    "Kattur",
    "Thuvakudi",
    "Ponmalai",
    "Crawford",
    "Melachinthamani",
    "Kallukuzhi",
    "TVS Tollgate",
    "Airport"
  ],
  "salem": [
    "Fairlands",
    "Alagapuram",
    "Hasthampatti",
    "Shevapet",
    "Gugai",
    "Suramangalam",
    "Ammapet",
    "Meyyanur",
    "Junction",
    "Narasothipatti",
    "Steel Plant",
    "Kondalampatti",
    "Seelanaickenpatti",
    "Kannankurichi",
    "Gorimedu"
  ],
  "kochi": [
    "MG Road",
    "Edappally",
    "Kakkanad",
    "Palarivattom",
    "Marine Drive",
    "Kaloor",
    "Fort Kochi",
    "Vyttila",
    "Panampilly Nagar",
    "Aluva",
    "Ernakulam North",
    "Ernakulam South",
    "Thevara",
    "Thoppumpady",
    "Mattancherry",
    "Kalamassery",
    "Angamaly",
    "Tripunithura",
    "Maradu",
    "Infopark",
    "SmartCity",
    "Kundannoor",
    "Ravipuram",
    "Chittoor",
    "Pachalam"
  ],
  "thiruvananthapuram": [
    "Kowdiar",
    "Vellayambalam",
    "Vazhuthacaud",
    "Sasthamangalam",
    "Pattom",
    "Kesavadasapuram",
    "Medical College",
    "Palayam",
    "Statue",
    "East Fort",
    "Thampanoor",
    "Karamana",
    "Poojappura",
    "Jagathy",
    "Kazhakkoottam",
    "Technopark",
    "Sreekaryam",
    "Ulloor",
    "Mannanthala",
    "Nemom",
    "Thiruvallam",
    "Kovalam",
    "Ambalamukku",
    "Pettah",
    "Attukal"
  ],
  "kozhikode": [
    "Mavoor Road",
    "Palayam",
    "SM Street",
    "Nadakkavu",
    "West Hill",
    "Bilathikulam",
    "Thondayad",
    "Pottammal",
    "Chevayur",
    "Eranhipalam",
    "Kottooli",
    "Medical College",
    "Feroke",
    "Pantheeramkavu",
    "Beypore",
    "Vellayil",
    "Meenchanda",
    "Mankavu",
    "Kallayi",
    "Civil Station"
  ],
  "thrissur": [
    "Swaraj Round",
    "East Fort",
    "West Fort",
    "Ayyanthole",
    "Punkunnam",
    "Koorkencherry",
    "Ollur",
    "Mannuthy",
    "Kuriachira",
    "Viyyur",
    "Ramavarmapuram",
    "Puzhakkal",
    "Sobha City",
    "Amballur",
    "Nadathara"
  ],
  "ahmedabad": [
    "Navrangpura",
    "SG Highway",
    "Satellite",
    "Vastrapur",
    "Bodakdev",
    "Maninagar",
    "Prahlad Nagar",
    "Chandkheda",
    "Bopal",
    "Thaltej",
    "Paldi",
    "Naranpura",
    "Ghatlodia",
    "Ranip",
    "Ellis Bridge",
    "Gurukul",
    "Memnagar",
    "Nikol",
    "Naroda",
    "C G Road",
    "Motera",
    "Sabarmati",
    "Gota",
    "Isanpur",
    "Odhav",
    "South Bopal",
    "Science City",
    "Sindhu Bhavan Road",
    "Ambawadi",
    "Usmanpura",
    "Vastral",
    "Amraiwadi",
    "CTM",
    "Vatva",
    "Kankaria",
    "Shahibaug",
    "Hansol",
    "Chandlodia",
    "Shela",
    "New Ranip"
  ],
  "surat": [
    "Adajan",
    "Vesu",
    "Piplod",
    "Varachha",
    "Katargam",
    "Rander",
    "Ghod Dod Road",
    "City Light",
    "Majura Gate",
    "Athwa",
    "Althan",
    "Pal",
    "Dumas Road",
    "Ring Road",
    "Textile Market",
    "Sachin GIDC",
    "Pandesara GIDC",
    "Hazira",
    "Udhana",
    "Bhatar",
    "Amroli",
    "Jahangirpura",
    "Nanpura",
    "Sarthana",
    "Mota Varachha"
  ],
  "vadodara": [
    "Alkapuri",
    "Gotri",
    "Vasna Road",
    "Sayajigunj",
    "Fatehgunj",
    "Akota",
    "Manjalpur",
    "Karelibaug",
    "Makarpura GIDC",
    "Waghodia Road",
    "Sama",
    "Subhanpura",
    "Gorwa",
    "Nizampura",
    "Ellora Park",
    "Tandalja",
    "Chhani",
    "New VIP Road",
    "Harni",
    "Atladara",
    "Bhayli",
    "Sevasi",
    "Vidyutnagar",
    "Padra Road",
    "Kalali"
  ],
  "rajkot": [
    "Kalawad Road",
    "Yagnik Road",
    "University Road",
    "150 Feet Ring Road",
    "Amin Marg",
    "Mavdi",
    "Gondal Road",
    "Bhaktinagar",
    "Aji GIDC",
    "Metoda GIDC",
    "Madhapar",
    "Kotecha Chowk",
    "Nana Mava",
    "Raiya Road",
    "Dhebar Road",
    "Tagore Road",
    "Kothariya",
    "Shapar",
    "Pedak Road",
    "Gandhigram"
  ],
  "jaipur": [
    "Malviya Nagar",
    "Vaishali Nagar",
    "Mansarovar",
    "C Scheme",
    "Raja Park",
    "Tonk Road",
    "Vidhyadhar Nagar",
    "Jagatpura",
    "Ajmer Road",
    "Gopalpura",
    "Sodala",
    "Bani Park",
    "Jhotwara",
    "Sanganer",
    "MI Road",
    "Civil Lines",
    "Bapu Nagar",
    "Shyam Nagar",
    "Nirman Nagar",
    "Sitapura",
    "VKIA",
    "Sindhi Camp",
    "Johari Bazar",
    "Amer Road",
    "Pratap Nagar",
    "Sirsi Road",
    "Kalwar Road",
    "Agra Road",
    "Delhi Road",
    "Chitrakoot"
  ],
  "jodhpur": [
    "Sardarpura",
    "Ratanada",
    "Shastri Nagar",
    "Paota",
    "Chopasni Housing Board",
    "Mandore",
    "Pal Road",
    "Basni",
    "Boranada",
    "Bhagat Ki Kothi",
    "Jalori Gate",
    "Sojati Gate",
    "Kudi Bhagtasni",
    "Residency Road",
    "Kamla Nehru Nagar"
  ],
  "udaipur": [
    "Panchwati",
    "Fatehpura",
    "Sukher",
    "Hiran Magri",
    "Madhuban",
    "Chetak Circle",
    "Saheli Nagar",
    "Goverdhan Vilas",
    "Mewar Industrial Area",
    "Bhuwana",
    "Shobhagpura",
    "Court Circle",
    "Surajpole",
    "Delhi Gate",
    "Pratap Nagar"
  ],
  "kota": [
    "Vigyan Nagar",
    "Talwandi",
    "Mahaveer Nagar",
    "Rajeev Gandhi Nagar",
    "Jawahar Nagar",
    "Dadabari",
    "Kunhari",
    "Gumanpura",
    "Indraprastha Industrial Area",
    "DCM Road",
    "Chawani",
    "Station Road",
    "Rangbari",
    "Borkhera",
    "Nayapura"
  ],
  "lucknow": [
    "Gomti Nagar",
    "Gomti Nagar Extension",
    "Hazratganj",
    "Alambagh",
    "Indira Nagar",
    "Mahanagar",
    "Aliganj",
    "Jankipuram",
    "Aminabad",
    "Chowk",
    "Ashiyana",
    "Rajajipuram",
    "Vikas Nagar",
    "Faizabad Road",
    "Kanpur Road",
    "Telibagh",
    "Charbagh",
    "Transport Nagar",
    "Amausi",
    "Sarojini Nagar",
    "Vibhuti Khand",
    "Vrindavan Yojna",
    "Kapoorthala",
    "Husainabad",
    "Daliganj",
    "Hussainganj",
    "Kaiserbagh",
    "Nishatganj",
    "Chinhat",
    "Dubagga"
  ],
  "kanpur": [
    "Civil Lines",
    "Swaroop Nagar",
    "Arya Nagar",
    "Tilak Nagar",
    "Kakadeo",
    "Kidwai Nagar",
    "Govind Nagar",
    "Saket Nagar",
    "Barra",
    "Kalyanpur",
    "Rawatpur",
    "Gumti No. 5",
    "Mall Road",
    "Fazalganj",
    "Panki",
    "Jajmau",
    "Cantt",
    "Shastri Nagar",
    "Chakeri",
    "Ratan Lal Nagar"
  ],
  "varanasi": [
    "Sigra",
    "Bhelupur",
    "Lanka",
    "Cantt",
    "Orderly Bazar",
    "Shivpur",
    "Pandeypur",
    "Mahmoorganj",
    "Godowlia",
    "Chowk",
    "Dashashwamedh",
    "Rathyatra",
    "Durgakund",
    "Nadesar",
    "Ramnagar",
    "Sarnath",
    "Ashapur",
    "Vidyapeeth",
    "Manduadih",
    "Rohania"
  ],
  "agra": [
    "Sanjay Place",
    "MG Road",
    "Kamla Nagar",
    "Dayalbagh",
    "Tajganj",
    "Shahganj",
    "Sikandra",
    "Bodla",
    "Fatehabad Road",
    "Khandari",
    "Sadar Bazar",
    "Belanganj",
    "Trans Yamuna",
    "Lohamandi",
    "Raja Ki Mandi"
  ],
  "prayagraj": [
    "Civil Lines",
    "George Town",
    "Ashok Nagar",
    "Tagore Town",
    "Katra",
    "Mumfordganj",
    "Kareli",
    "Dhoomanganj",
    "Naini",
    "Phaphamau",
    "Jhalwa",
    "Jhusi",
    "Chowk",
    "Lukarganj",
    "Allahpur"
  ],
  "meerut": [
    "Shastri Nagar",
    "Ganga Nagar",
    "Pallavpuram",
    "Modipuram",
    "Begum Bridge",
    "Abu Lane",
    "Sadar Bazar",
    "Delhi Road",
    "Partapur",
    "Hapur Road",
    "Kanker Khera",
    "Baghpat Road",
    "Garh Road",
    "Jagriti Vihar",
    "Suraj Kund"
  ],
  "dehradun": [
    "Rajpur Road",
    "Jakhan",
    "Sahastradhara Road",
    "Ballupur",
    "Chakrata Road",
    "Clement Town",
    "GMS Road",
    "Haridwar Road",
    "Patel Nagar",
    "Subhash Nagar",
    "Selaqui",
    "IT Park",
    "Dharampur",
    "Race Course",
    "Vasant Vihar",
    "Hathibarkala",
    "Karanpur",
    "Prem Nagar",
    "Turner Road",
    "ISBT"
  ],
  "haridwar": [
    "Ranipur",
    "Jwalapur",
    "SIDCUL",
    "Kankhal",
    "Har Ki Pauri",
    "Shivalik Nagar",
    "Bahadrabad",
    "Bhel",
    "Roshnabad",
    "Bhupatwala"
  ],
  "indore": [
    "Vijay Nagar",
    "Palasia",
    "New Palasia",
    "Old Palasia",
    "Rajwada",
    "Bhanwarkuan",
    "AB Road",
    "Sapna Sangeeta",
    "Annapurna",
    "Saket",
    "Bengali Square",
    "Rau",
    "Super Corridor",
    "MR 10",
    "Scheme 54",
    "Scheme 78",
    "Geeta Bhawan",
    "Chhavani",
    "Pithampur",
    "Sanwer Road",
    "Sudama Nagar",
    "Lokmanya Nagar",
    "Manik Bagh",
    "Chandan Nagar",
    "Khajrana"
  ],
  "bhopal": [
    "MP Nagar",
    "Arera Colony",
    "Bittan Market",
    "Kolar Road",
    "Hoshangabad Road",
    "Shahpura",
    "Chunabhatti",
    "Habibganj",
    "TT Nagar",
    "New Market",
    "Malviya Nagar",
    "Govindpura",
    "Mandideep",
    "Bairagarh",
    "Ayodhya Bypass",
    "Indrapuri",
    "Jahangirabad",
    "Peer Gate",
    "Bhadbhada Road",
    "Karond"
  ],
  "gwalior": [
    "City Centre",
    "Lashkar",
    "Morar",
    "Thatipur",
    "Phoolbagh",
    "Maharaj Bada",
    "Padav",
    "Deen Dayal Nagar",
    "Malanpur",
    "Banmore",
    "Pinto Park",
    "Hazira",
    "Bahodapur",
    "Govindpuri",
    "Gole Ka Mandir"
  ],
  "jabalpur": [
    "Wright Town",
    "Napier Town",
    "Civil Lines",
    "Russell Chowk",
    "Gorakhpur",
    "Madan Mahal",
    "Vijay Nagar",
    "Adhartal",
    "Richhai",
    "Ghamapur",
    "Ranjhi",
    "Garha",
    "Gwarighat",
    "Sadar",
    "Kotwali"
  ],
  "raipur": [
    "Pandri",
    "Telibandha",
    "Shankar Nagar",
    "Devendra Nagar",
    "Civil Lines",
    "Samta Colony",
    "Tatibandh",
    "Gudhiyari",
    "VIP Road",
    "GE Road",
    "Urla",
    "Siltara",
    "Naya Raipur",
    "Mowa",
    "DDU Nagar",
    "Khamardih",
    "Bhatagaon",
    "Pachpedi Naka",
    "Santoshi Nagar",
    "Amanaka"
  ],
  "kolkata": [
    "Park Street",
    "Salt Lake",
    "New Town",
    "Ballygunge",
    "Gariahat",
    "Behala",
    "Dum Dum",
    "Howrah",
    "Jadavpur",
    "Tollygunge",
    "Alipore",
    "Bhowanipore",
    "Shyambazar",
    "Kankurgachi",
    "Rajarhat",
    "Lake Town",
    "Kasba",
    "Baguiati",
    "Barasat",
    "Garia",
    "Jorasanko",
    "Sealdah",
    "Esplanade",
    "Rash Behari",
    "Ultadanga",
    "Taratala",
    "Cossipore",
    "Camac Street",
    "Chowringhee",
    "BBD Bagh",
    "College Street",
    "Sovabazar",
    "Hatibagan",
    "Maniktala",
    "Phoolbagan",
    "Bangur",
    "Nagerbazar",
    "Kestopur",
    "VIP Road",
    "EM Bypass",
    "Topsia",
    "Tangra",
    "Park Circus",
    "Golpark",
    "Dhakuria",
    "Jodhpur Park",
    "Lake Gardens",
    "Kudghat",
    "Santoshpur",
    "Ruby",
    "Mukundapur",
    "New Alipore",
    "Kalighat",
    "Southern Avenue",
    "Prince Anwar Shah Road"
  ],
  "patna": [
    "Boring Road",
    "Boring Canal Road",
    "Fraser Road",
    "Bailey Road",
    "Kankarbagh",
    "Rajendra Nagar",
    "Patliputra Colony",
    "Ashiana Nagar",
    "Digha",
    "Danapur",
    "Exhibition Road",
    "Dak Bungalow",
    "Gandhi Maidan",
    "Anisabad",
    "Phulwari Sharif",
    "Raja Bazar",
    "Saguna More",
    "Jagdeo Path",
    "Kumhrar",
    "Gola Road",
    "SK Puri",
    "Kidwaipuri",
    "Buddha Colony",
    "Rukunpura",
    "Kurji"
  ],
  "bhubaneswar": [
    "Saheed Nagar",
    "Jayadev Vihar",
    "Nayapalli",
    "Chandrasekharpur",
    "Patia",
    "Infocity",
    "Khandagiri",
    "Rasulgarh",
    "Mancheswar",
    "Master Canteen",
    "Bapuji Nagar",
    "Kharavela Nagar",
    "Unit 1",
    "Unit 2",
    "Unit 3",
    "Unit 4",
    "Unit 6",
    "Unit 8",
    "Unit 9",
    "KIIT Square",
    "Sailashree Vihar",
    "Niladri Vihar",
    "Baramunda",
    "Old Town",
    "Laxmisagar",
    "Satya Nagar",
    "Surya Nagar",
    "Sundarpada",
    "Jatani",
    "Tamando"
  ],
  "cuttack": [
    "Badambadi",
    "Ranihat",
    "Mangalabag",
    "Choudhry Bazar",
    "Buxi Bazar",
    "Link Road",
    "CDA Sector 1",
    "CDA Sector 6",
    "CDA Sector 9",
    "Jagatpur",
    "Madhupatna",
    "College Square",
    "Jobra",
    "Tulasipur",
    "Chhatra Bazar"
  ],
  "ranchi": [
    "Lalpur",
    "Main Road",
    "Doranda",
    "Hinoo",
    "Harmu",
    "Ashok Nagar",
    "Morabadi",
    "Bariatu",
    "Kanke Road",
    "Ratu Road",
    "Namkum",
    "Tatisilwai",
    "Kokar",
    "Dhurwa",
    "HEC Township",
    "Argora",
    "Chutia",
    "Kadru",
    "Pandra",
    "Kantatoli"
  ],
  "jamshedpur": [
    "Bistupur",
    "Sakchi",
    "Kadma",
    "Sonari",
    "Telco",
    "Baridih",
    "Golmuri",
    "Adityapur",
    "Gamharia",
    "Mango",
    "Sidhgora",
    "Jugsalai",
    "Burmamines",
    "Parsudih",
    "Agrico"
  ],
  "dhanbad": [
    "Bank More",
    "Saraidhela",
    "Hirapur",
    "Steel Gate",
    "Bartand",
    "Katras",
    "Jharia",
    "Govindpur",
    "Dhansar",
    "Karmik Nagar",
    "Chirkunda",
    "Barwadda",
    "Putki",
    "Sindri",
    "Kusunda"
  ],
  "guwahati": [
    "GS Road",
    "Christian Basti",
    "Dispur",
    "Paltan Bazar",
    "Pan Bazar",
    "Fancy Bazar",
    "Ganeshguri",
    "Bhangagarh",
    "Zoo Road",
    "Ulubari",
    "Jalukbari",
    "Maligaon",
    "Beltola",
    "Six Mile",
    "Hatigaon",
    "Khanapara",
    "Kahilipara",
    "Lokhra",
    "Borjhar",
    "Noonmati",
    "Chandmari",
    "Uzan Bazar",
    "Rehabari",
    "Silpukhuri",
    "Lachit Nagar"
  ],
  "chandigarh": [
    "Sector 17",
    "Sector 35",
    "Sector 22",
    "Sector 8",
    "Sector 9",
    "Sector 26",
    "Sector 34",
    "Sector 43",
    "Sector 7",
    "Sector 11",
    "Sector 15",
    "Sector 20",
    "Sector 32",
    "Sector 44",
    "Industrial Area Phase 1",
    "Industrial Area Phase 2",
    "Mohali",
    "Panchkula",
    "Manimajra",
    "Zirakpur",
    "Kharar",
    "Sector 68 Mohali",
    "Sector 70 Mohali",
    "Sector 82 Mohali",
    "MDC Panchkula"
  ],
  "ludhiana": [
    "Model Town",
    "Sarabha Nagar",
    "Ferozepur Road",
    "Civil Lines",
    "BRS Nagar",
    "South City",
    "Ghumar Mandi",
    "Pakhowal Road",
    "Focal Point",
    "Industrial Area A",
    "Industrial Area B",
    "Miller Ganj",
    "Gill Road",
    "Samrala Chowk",
    "Dhandari Kalan",
    "Dugri",
    "Kitchlu Nagar",
    "Tagore Nagar",
    "Jodhewal",
    "Sherpur"
  ],
  "amritsar": [
    "Mall Road",
    "Ranjit Avenue",
    "Lawrence Road",
    "Court Road",
    "Circular Road",
    "Majitha Road",
    "GT Road",
    "Hall Bazar",
    "Katra Jaimal Singh",
    "Putlighar",
    "Chheharta",
    "Batala Road",
    "Albert Road",
    "Green Avenue",
    "Civil Lines"
  ],
  "jalandhar": [
    "Model Town",
    "Jalandhar Cantt",
    "Nakodar Road",
    "GT Road",
    "PPR Mall Road",
    "Urban Estate Phase 1",
    "Urban Estate Phase 2",
    "Focal Point",
    "Leather Complex",
    "Rama Mandi",
    "BMC Chowk",
    "Jyoti Chowk",
    "Ladowali Road",
    "Civil Lines",
    "Mota Singh Nagar"
  ],
  "srinagar": [
    "Lal Chowk",
    "Rajbagh",
    "Jawahar Nagar",
    "Karan Nagar",
    "Sonwar",
    "Dalgate",
    "Boulevard Road",
    "Hyderpora",
    "Sanat Nagar",
    "Soura",
    "Hazratbal",
    "Batamaloo",
    "Bemina",
    "Nowhatta",
    "Baghat"
  ],
  "jammu": [
    "Gandhi Nagar",
    "Trikuta Nagar",
    "Channi Himmat",
    "Bahu Plaza",
    "Shastri Nagar",
    "Talab Tillo",
    "Janipur",
    "Bari Brahmana",
    "Gangyal",
    "Resham Ghar",
    "Bakshi Nagar",
    "Rehari Colony",
    "Nanak Nagar",
    "Kachi Chawni",
    "Jewel Chowk"
  ],
  "shimla": [
    "The Mall",
    "Lakkar Bazar",
    "Sanjauli",
    "Chotta Shimla",
    "New Shimla",
    "Kasumpti",
    "Boileauganj",
    "Summer Hill",
    "Totu",
    "Dhalli",
    "Jakhu",
    "Kaithu",
    "Tara Devi",
    "Shoghi",
    "Mashobra"
  ]
};

export const CITY_ALIASES = {
  "bengaluru": "bangalore",
  "blr": "bangalore",
  "bombay": "mumbai",
  "bom": "mumbai",
  "new delhi": "delhi",
  "delhi ncr": "delhi",
  "ncr": "delhi",
  "dilli": "delhi",
  "gurugram": "gurgaon",
  "ggn": "gurgaon",
  "greater noida": "noida",
  "calcutta": "kolkata",
  "ccu": "kolkata",
  "madras": "chennai",
  "maa": "chennai",
  "secunderabad": "hyderabad",
  "hyd": "hyderabad",
  "cyberabad": "hyderabad",
  "poona": "pune",
  "pimpri chinchwad": "pune",
  "pcmc": "pune",
  "amdavad": "ahmedabad",
  "ahmedabad city": "ahmedabad",
  "cochin": "kochi",
  "ernakulam": "kochi",
  "trivandrum": "thiruvananthapuram",
  "calicut": "kozhikode",
  "vizag": "visakhapatnam",
  "waltair": "visakhapatnam",
  "bezawada": "vijayawada",
  "baroda": "vadodara",
  "trichy": "trichy",
  "tiruchirappalli": "trichy",
  "tiruchirapalli": "trichy",
  "allahabad": "prayagraj",
  "banaras": "varanasi",
  "kashi": "varanasi",
  "chhatrapati sambhaji nagar": "aurangabad",
  "sambhajinagar": "aurangabad",
  "sas nagar": "chandigarh",
  "mohali": "chandigarh",
  "panchkula": "chandigarh",
  "orissa": "bhubaneswar",
  "bbsr": "bhubaneswar",
  "panaji": "goa",
  "north goa": "goa",
  "south goa": "goa"
};

const DEFAULT_AREAS = [
  'Central', 'North', 'South', 'East', 'West',
  'Market', 'Main Road', 'Station Road', 'City Center', 'Industrial Area',
  'Civil Lines', 'Commercial Complex', 'MIDC', 'GIDC', 'Model Town'
];

/**
 * Returns canonical list of major localities for a given normalized city
 */
export function getCityAreas(city) {
  if (!city) return DEFAULT_AREAS;
  const key = String(city).trim().toLowerCase();
  
  // Resolve direct match
  if (CITY_AREAS[key]) {
    return CITY_AREAS[key];
  }
  
  // Resolve alias
  if (CITY_ALIASES[key] && CITY_AREAS[CITY_ALIASES[key]]) {
    return CITY_AREAS[CITY_ALIASES[key]];
  }

  // Substring / fuzzy match against known cities
  for (const [cityName, areas] of Object.entries(CITY_AREAS)) {
    if (key.includes(cityName) || cityName.includes(key)) {
      return areas;
    }
  }

  return DEFAULT_AREAS;
}
